/**
 * Numerical parameters of the game.
 * Values are synced with balance.yaml. No numeric magic numbers should be hardcoded in logic.
 */
export const BALANCE = {
  PERFORMANCE: {
    TARGET_FPS: 60,
    MAX_DRAW_CALLS: 75,
    MAX_TRIANGLES: 45000,
    BUNDLE_SIZE_BUDGET_MB: 4.5,
  },
  SESSION: {
    ROUNDS_TO_WIN: 3,
    MAX_ROUNDS: 5,
    ROUND_TIME_LIMIT_SEC: 45.0,
    FREEZE_TIME_SEC: 2.0,
    ROUND_END_DELAY_SEC: 3.5,
  },
  COUNTER_STRAFE: {
    IDEAL_TIMING_SEC: 0.08,
    ZERO_INACCURACY_THRESHOLD_UNITS: 34.0, // 0.85 m/s (1 unit = 0.025m)
    MAX_RUN_SPEED_AK47: 215.0, // 5.375 m/s
    RUNNING_INACCURACY_PENALTY_MOA: 85.0,
    MAX_VELOCITY_UNITS: 250.0,
    DECELERATION_FRICTION: 8.5,
    COUNTER_BRAKE_MULTIPLIER: 0.15,
  },
  RECOIL: {
    AK47_VERTICAL_CLIMB_DEG: 2.4,
    M4A4_VERTICAL_CLIMB_DEG: 1.8,
    AWP_VERTICAL_CLIMB_DEG: 6.0,
    DEAGLE_VERTICAL_CLIMB_DEG: 3.2,
    RECOIL_DECAY_SEC: 0.32,
    FIRE_RATE_AK47_RPM: 600, // 10 shots/sec
    FIRE_RATE_M4A4_RPM: 660, // 11 shots/sec
    FIRE_RATE_AWP_RPM: 40,   // ~1.5 sec delay
    FIRE_RATE_DEAGLE_RPM: 260,
    HORIZONTAL_SPREAD_SWING_DEG: 1.8,
  },
  C4: {
    BASE_DEFUSE_TIME_SEC: 10.0,
    KIT_DEFUSE_TIME_SEC: 5.0,
    DETONATOR_TIMER_SEC: 35.0,
    INTERACTION_RADIUS_METERS: 2.2,
    EXPLOSION_RADIUS_METERS: 28.0,
  },
  SMOKE: {
    DENSE_PHASE_DURATION_SEC: 12.0,
    CLOUD_RADIUS_METERS: 4.2,
    EXPANSION_TIME_SEC: 1.2,
    DETONATION_DELAY_SEC: 1.5,
    DISSIPATION_TIME_SEC: 2.5,
  },
  WALLBANG: {
    WOOD_DAMAGE_RETENTION: 0.60,
    MAX_WOOD_PENETRATION_DEPTH_METERS: 0.35,
    METAL_PENETRATION_RETENTION: 0.30,
    VELOCITY_DROP_AFTER_OBSTACLE: 0.45,
  },
  BOT_AI: {
    BASE_REACTION_TIME_MS: 450.0,
    MIN_REACTION_TIME_MS: 180.0,
    REACTION_STREAK_STEP_MS: 45.0,
    REACTION_RANK_STEP_MS: 25.0,
    HEARING_RADIUS_METERS: 16.0,
    VISION_FOV_DEG: 90.0,
    VISION_RANGE_METERS: 40.0,
  },
  ELO: {
    MATCH_WIN_BASE: 25,
    MATCH_LOSS_BASE: 20,
    HEADSHOT_BONUS: 2,
    DEFUSE_BONUS: 5,
    CLUTCH_BONUS: 10,
  },
} as const;

export type BalanceConfig = typeof BALANCE;
