import * as THREE from 'three';
import type { Level, AimSegment } from '../types';
import { neon } from './Shaders';
import { Enemy } from '../entities/Enemy';
export class SceneManager { readonly scene = new THREE.Scene(); readonly camera = new THREE.PerspectiveCamera(65, 1, .1, 100); readonly renderer: THREE.WebGLRenderer; readonly laser = new THREE.Line(new THREE.BufferGeometry(), neon(0x49f6ff)); readonly bullet = new THREE.Mesh(new THREE.SphereGeometry(.11, 12, 8), neon(0xffe27a)); readonly enemies: Enemy[] = []; private readonly root = new THREE.Group(); private readonly wallMaterial = new THREE.MeshLambertMaterial({ color: 0x48515e }); private readonly enemyMaterial = new THREE.MeshLambertMaterial({ color: 0xff315c }); constructor(host: HTMLElement) { this.renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: 'high-performance' }); this.renderer.setPixelRatio(Math.min(devicePixelRatio, 1.5)); this.renderer.shadowMap.enabled = true; host.appendChild(this.renderer.domElement); this.scene.background = new THREE.Color(0x07111d); this.scene.add(new THREE.HemisphereLight(0x9ddcff, 0x10151d, 1.5)); const sun = new THREE.DirectionalLight(0xffffff, 2.2); sun.position.set(4, 8, 5); sun.castShadow = true; this.scene.add(sun); this.scene.add(this.root, this.laser, this.bullet); this.camera.position.set(0, 1.5, 5); this.camera.lookAt(0, 1, -4); window.addEventListener('resize', this.resize); this.resize(); }
 load(level: Level): void { this.root.clear(); this.enemies.length = 0; for (const wall of level.walls) { const mesh = new THREE.Mesh(new THREE.BoxGeometry(...wall.size), this.wallMaterial); mesh.position.set(...wall.position); mesh.rotation.y = wall.rotation ?? 0; mesh.receiveShadow = true; this.root.add(mesh); } for (const target of level.targets) { if (target.kind === 'enemy') { const enemy = new Enemy(new THREE.Vector3(...target.position), this.enemyMaterial); this.enemies.push(enemy); this.root.add(enemy.mesh); } else { const barrel = new THREE.Mesh(new THREE.CylinderGeometry(.38, .38, 1, 12), neon(0xffa227)); barrel.position.set(...target.position); barrel.position.y = .5; barrel.rotation.z = Math.PI / 2; this.root.add(barrel); } } for (const portal of level.portals) { const ring = new THREE.Mesh(new THREE.TorusGeometry(.7, .07, 8, 24), neon(portal.color === 'blue' ? 0x27a9ff : 0xff7b2b)); ring.position.set(...portal.position); ring.rotation.y = Math.PI / 2; this.root.add(ring); } this.bullet.visible = false; }
 setLaser(segments: AimSegment[]): void { const positions = new Float32Array(segments.length * 6); segments.forEach((segment, i) => { positions.set([segment.from.x, segment.from.y, segment.from.z, segment.to.x, segment.to.y, segment.to.z], i * 6); }); this.laser.geometry.dispose(); this.laser.geometry = new THREE.BufferGeometry(); this.laser.geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3)); }
 render(): void { this.renderer.render(this.scene, this.camera); } resize = (): void => { this.camera.aspect = innerWidth / innerHeight; this.camera.updateProjectionMatrix(); this.renderer.setSize(innerWidth, innerHeight, false); };
}
