import * as THREE from 'three';
import { EventBus } from './EventBus';
import { GameLoop } from './GameLoop';
import { SceneManager } from '../rendering/SceneManager';
import { LevelManager, boundsFor } from '../systems/LevelManager';
import { LaserPredictor } from '../systems/LaserPredictor';
import { Weapon } from '../entities/Weapon';
import { Player } from '../entities/Player';
import { UIManager } from '../ui/UIManager';
import { TouchControls } from '../ui/TouchControls';
import { AudioManager } from '../audio/AudioManager';
import { StorageService } from '../platform/StorageService';
import { PhysicsWorld } from '../physics/PhysicsWorld';
import type { GameMode, InputSnapshot } from '../types';
export class Game { private readonly bus = new EventBus(); private readonly levels = new LevelManager(); private readonly predictor = new LaserPredictor(); private readonly weapon = new Weapon(); private readonly player = new Player(); private readonly audio = new AudioManager(); private readonly storage = new StorageService(); private readonly physics = new PhysicsWorld(); private readonly scene: SceneManager; private readonly ui: UIManager; private readonly touch: TouchControls; private readonly input: InputSnapshot = { aimX: 0, aimY: 0, fire: false, boost: false, pause: false }; private mode: GameMode = 'menu'; private shots = 0; private flightTime = 0; private segmentIndex = 0; private bulletVelocity = new THREE.Vector3(); private readonly bulletPosition = new THREE.Vector3(); private loop: GameLoop;
 constructor(host: HTMLElement) { this.scene = new SceneManager(host); this.ui = new UIManager({ start: () => this.start(), restart: () => this.restart(), next: () => this.next(), pause: () => this.togglePause() }); this.touch = new TouchControls((value) => Object.assign(this.input, value)); this.ui.root.appendChild(this.touch.element); host.appendChild(this.ui.root); this.installInput(); this.loop = new GameLoop((dt) => this.update(dt), () => this.render()); this.scene.load(this.levels.load(1)); this.ui.setMode('menu', 1, 0); void this.physics.init(); }
 async boot(): Promise<void> { await this.storage.load(); this.scene.load(this.levels.load(this.storage.data.unlockedLevel)); }
 start(): void { this.mode = 'aim'; this.shots = 0; this.touch.setVisible(true); this.ui.setMode('aim', this.levels.current + 1, this.shots); this.loop.start(); this.audio.beep(440); }
 restart(): void { this.mode = 'aim'; this.shots = 0; this.flightTime = 0; this.scene.load(this.levels.level); this.touch.setVisible(true); this.ui.setMode('aim', this.levels.current + 1, this.shots); }
 next(): void { if (this.levels.current < 19) { this.levels.load(this.levels.current + 2); this.restart(); } }
 togglePause(): void { if (this.mode === 'aim') { this.mode = 'paused'; this.touch.setVisible(false); } else if (this.mode === 'paused') { this.mode = 'aim'; this.touch.setVisible(true); } this.ui.setMode(this.mode, this.levels.current + 1, this.shots); }
 private installInput(): void { window.addEventListener('keydown', (event) => { if (event.code === 'KeyR') this.restart(); if (event.code === 'Escape' || event.code === 'KeyP') this.togglePause(); if (event.code === 'Space') this.input.boost = true; if (event.code === 'KeyJ') this.input.fire = true; }); window.addEventListener('keyup', (event) => { if (event.code === 'Space') this.input.boost = false; if (event.code === 'KeyJ') this.input.fire = false; }); window.addEventListener('pointermove', (event) => { if (this.mode !== 'aim' || event.clientX < innerWidth * .5) return; this.input.aimX = (event.clientX / innerWidth - .5) * 2; this.input.aimY = -(event.clientY / innerHeight - .5) * 2; }); window.addEventListener('pointerdown', (event) => { if (this.mode === 'aim' && event.button === 0 && event.clientX >= innerWidth * .5) this.input.fire = true; }); window.addEventListener('pointerup', () => { this.input.fire = false; }); }
 private fire(): void { this.weapon.setAim(this.input.aimX, this.input.aimY); const surfaces = boundsFor(this.levels.level); const segments = this.predictor.predict(this.weapon.muzzle, this.weapon.direction, surfaces); this.scene.setLaser(segments); this.bulletPosition.copy(this.weapon.muzzle); this.bulletVelocity.copy(this.weapon.direction).multiplyScalar(16); this.segmentIndex = 0; this.flightTime = 0; this.shots++; this.mode = 'flight'; this.touch.setVisible(false); this.scene.bullet.visible = true; this.ui.setMode('flight', this.levels.current + 1, this.shots); this.audio.beep(180); this.bus.emit('shot:fired', undefined); }
 private update(dt: number): void { if (this.mode === 'aim') { this.weapon.setAim(this.input.aimX, this.input.aimY); this.scene.setLaser(this.predictor.predict(this.weapon.muzzle, this.weapon.direction, boundsFor(this.levels.level))); if (this.input.fire) { this.input.fire = false; this.fire(); } } else if (this.mode === 'flight') this.updateFlight(dt * (this.input.boost ? 3 : .22)); for (const enemy of this.scene.enemies) enemy.update(dt); this.physics.step(); }
 private updateFlight(dt: number): void { this.flightTime += dt; this.bulletPosition.addScaledVector(this.bulletVelocity, dt); this.scene.bullet.position.copy(this.bulletPosition); for (const enemy of this.scene.enemies) { if (enemy.alive && enemy.mesh.position.distanceTo(this.bulletPosition) < .7) { enemy.hit(this.bulletVelocity); this.bus.emit('target:hit', { kind: 'enemy' }); this.audio.beep(90); } } if (this.flightTime > 5 || this.bulletPosition.z < -18) { this.scene.bullet.visible = false; if (this.scene.enemies.every((enemy) => !enemy.alive)) this.win(); else this.restart(); } }
 private win(): void { this.mode = 'won'; const stars = this.shots === 1 ? 3 : this.shots === 2 ? 2 : 1; this.storage.data.stars[this.levels.current] = Math.max(this.storage.data.stars[this.levels.current], stars); this.storage.data.unlockedLevel = Math.max(this.storage.data.unlockedLevel, Math.min(20, this.levels.current + 2)); this.storage.save(); this.touch.setVisible(false); this.ui.setMode('won', this.levels.current + 1, this.shots, stars); this.audio.beep(660, .2); }
 private render(): void { if (this.mode === 'flight') { const target = this.bulletPosition.clone().add(new THREE.Vector3(.7, .4, 1.4)); this.scene.camera.position.lerp(target, .08); this.scene.camera.lookAt(this.bulletPosition); } else { this.scene.camera.position.lerp(new THREE.Vector3(0, 1.5, 5), .12); this.scene.camera.lookAt(0, 1, -4); } this.scene.render(); }
}
