import { CarDefinition, TrackDefinition, PlayerSaveData } from '../types';

export const CONFIG = {
  game: {
    title: 'Ночной спринт: Трафик и Закись',
    version: '1.0.0',
    slug: 'night-sprint-traffic-nitro',
  },
  physics: {
    fixedTimestep: 1 / 60,
    gravityY: -14.0,
    deltaClamp: 0.10,
    wheelRayGroup: 0x0002,
    groundGroup: 0x0001,
  },
  combo: {
    baseNitroGain: 18.0, // %
    opposingMultiplier: 2.2,
    slingshotBoostKmh: 35.0,
    slingshotChargeTime: 1.2,
    slingshotMaxDist: 8.0,
    slingshotMaxLateral: 0.8,
    nearMissCriticalDist: 1.2,
    nearMissMinSpeedKmh: 120.0,
    nearMissMaxLateral: 1.2,
    flickTimingWindow: 0.28,
    driftOptimalAngle: 28.0,
    driftVelocityRetention: 0.92,
    maxComboMultiplier: 5.0,
  },
  nitro: {
    burnRateStage1: 18.0, // %/sec
    burnRateStage2: 35.0,
    torqueBoostStage1: 1.45,
    torqueBoostStage2: 1.90,
    fovBase: 60.0,
    fovStage1: 80.0,
    fovStage2: 92.0,
  },
  ads: {
    interstitialCooldownSec: 90,
    reviveCooldownSec: 60,
    reviveInvulnerableSec: 3.0,
  },
  ui: {
    safeAreaInset: 'calc(18px + env(safe-area-inset-bottom))',
    colors: {
      gold: '#ffd700',
      cyan: '#00f0ff',
      magenta: '#ff007f',
      blue: '#2979ff',
      purple: '#7928ca',
      red: '#ff0033',
      dark: '#0d1117',
      gray: '#1f293e',
    },
  },
};

export const CAR_CATALOG: CarDefinition[] = [
  {
    id: 'car_hatch_s',
    name: 'KAIZEN CIVIC R-SPEC',
    category: 'Street Tuner',
    price: 0,
    repRequired: 0,
    description: 'Легкий и юркий переднеприводный хэтчбек. Идеален для филигранного лавирования в потоке.',
    baseStats: {
      topSpeedKmh: 210,
      acceleration0to100: 5.2,
      handlingGrip: 0.82,
      nitroCapacitySec: 4.0,
      massKg: 1150,
      horsepower: 195,
    },
    defaultBodyColor: '#ffffff',
    defaultNeonColor: '#00f0ff',
    bodyMeshType: 'hatch',
  },
  {
    id: 'car_drift_s13',
    name: 'SILVIA S15 MIDNIGHT RUNNER',
    category: 'Drift Spec',
    price: 15000,
    repRequired: 400,
    description: 'Культовое заднеприводное купе с острым рулем. Королева скандинавского щелчка.',
    baseStats: {
      topSpeedKmh: 235,
      acceleration0to100: 4.4,
      handlingGrip: 0.88,
      nitroCapacitySec: 4.5,
      massKg: 1240,
      horsepower: 280,
    },
    defaultBodyColor: '#7928ca',
    defaultNeonColor: '#ff007f',
    bodyMeshType: 'coupe',
  },
  {
    id: 'car_muscle_gt',
    name: 'DOMINATOR GT-V8',
    category: 'Muscle Monster',
    price: 35000,
    repRequired: 1200,
    description: 'Тяжелый американский маслкар с компрессорным V8. Сметает все на прямых участках.',
    baseStats: {
      topSpeedKmh: 255,
      acceleration0to100: 3.8,
      handlingGrip: 0.74,
      nitroCapacitySec: 5.0,
      massKg: 1580,
      horsepower: 460,
    },
    defaultBodyColor: '#d4af37',
    defaultNeonColor: '#ffd700',
    bodyMeshType: 'muscle',
  },
  {
    id: 'car_super_v10',
    name: 'TORO LP-560 V10',
    category: 'Exotic Supercar',
    price: 75000,
    repRequired: 3000,
    description: 'Итальянский полноприводный суперкар с высокооборотистым V10. Хищный силуэт и бешеная динамика.',
    baseStats: {
      topSpeedKmh: 275,
      acceleration0to100: 3.2,
      handlingGrip: 0.91,
      nitroCapacitySec: 5.5,
      massKg: 1380,
      horsepower: 560,
    },
    defaultBodyColor: '#00f0ff',
    defaultNeonColor: '#00f0ff',
    bodyMeshType: 'super',
  },
  {
    id: 'car_apex_gtr',
    name: 'APEX GT-R 35 GODZILLA',
    category: 'AWD Track Beast',
    price: 120000,
    repRequired: 6500,
    description: 'Легендарный полноприводный монстр с битурбо V6. Стабилен в любых миллиметровых разъездах.',
    baseStats: {
      topSpeedKmh: 295,
      acceleration0to100: 2.7,
      handlingGrip: 0.95,
      nitroCapacitySec: 6.0,
      massKg: 1440,
      horsepower: 680,
    },
    defaultBodyColor: '#ff073a',
    defaultNeonColor: '#ff073a',
    bodyMeshType: 'gtr',
  },
  {
    id: 'car_hyper_phantom',
    name: 'PHANTOM VENENO CYBER',
    category: 'Apex Hypercar',
    price: 250000,
    repRequired: 14000,
    description: 'Ультимативный карбоновый гиперкар высшей лиги. Сверхзвуковой форсаж свыше 320 км/ч.',
    baseStats: {
      topSpeedKmh: 320,
      acceleration0to100: 2.2,
      handlingGrip: 0.98,
      nitroCapacitySec: 6.5,
      massKg: 1180,
      horsepower: 850,
    },
    defaultBodyColor: '#2979ff',
    defaultNeonColor: '#7928ca',
    bodyMeshType: 'hyper',
  },
];

export const TRACK_CATALOG: TrackDefinition[] = [
  // District 1: Залив (Bay District)
  {
    id: 'track_01',
    name: 'Шоссе над заливом: Полночь',
    district: 'Залив',
    districtId: 1,
    lengthMeters: 2400,
    baseTimeLimitSec: 75,
    targetGoldSec: 62,
    targetSilverSec: 68,
    targetBronzeSec: 75,
    trafficDensity: 0.22,
    oncomingProbability: 0.15,
    theme: 'highway',
    rewardCash: 2500,
    rewardRep: 150,
  },
  {
    id: 'track_02',
    name: 'Эстакада залива: Рассвет',
    district: 'Залив',
    districtId: 1,
    lengthMeters: 2600,
    baseTimeLimitSec: 80,
    targetGoldSec: 66,
    targetSilverSec: 72,
    targetBronzeSec: 80,
    trafficDensity: 0.26,
    oncomingProbability: 0.20,
    theme: 'highway',
    rewardCash: 3000,
    rewardRep: 200,
  },
  {
    id: 'track_03',
    name: 'Побережье: Штормовой спринт',
    district: 'Залив',
    districtId: 1,
    lengthMeters: 2800,
    baseTimeLimitSec: 85,
    targetGoldSec: 70,
    targetSilverSec: 76,
    targetBronzeSec: 85,
    trafficDensity: 0.30,
    oncomingProbability: 0.25,
    theme: 'highway',
    rewardCash: 3500,
    rewardRep: 250,
  },

  // District 2: Портовый тоннель (Harbor Tunnel)
  {
    id: 'track_04',
    name: 'Портовый тоннель: Оранжевый неон',
    district: 'Портовый тоннель',
    districtId: 2,
    lengthMeters: 2500,
    baseTimeLimitSec: 75,
    targetGoldSec: 62,
    targetSilverSec: 68,
    targetBronzeSec: 75,
    trafficDensity: 0.35,
    oncomingProbability: 0.25,
    theme: 'tunnel',
    rewardCash: 4000,
    rewardRep: 300,
  },
  {
    id: 'track_05',
    name: 'Индустриальный затор: Час пик',
    district: 'Портовый тоннель',
    districtId: 2,
    lengthMeters: 2700,
    baseTimeLimitSec: 80,
    targetGoldSec: 65,
    targetSilverSec: 72,
    targetBronzeSec: 80,
    trafficDensity: 0.40,
    oncomingProbability: 0.30,
    theme: 'tunnel',
    rewardCash: 4500,
    rewardRep: 350,
  },
  {
    id: 'track_06',
    name: 'Портовый терминал: Сквозной форсаж',
    district: 'Портовый тоннель',
    districtId: 2,
    lengthMeters: 2900,
    baseTimeLimitSec: 85,
    targetGoldSec: 69,
    targetSilverSec: 76,
    targetBronzeSec: 85,
    trafficDensity: 0.45,
    oncomingProbability: 0.32,
    theme: 'tunnel',
    rewardCash: 5000,
    rewardRep: 400,
  },

  // District 3: Неоновый Даунтаун (Downtown Skyline)
  {
    id: 'track_07',
    name: 'Неоновый проспект: Киберпанк',
    district: 'Неоновый Даунтаун',
    districtId: 3,
    lengthMeters: 2600,
    baseTimeLimitSec: 78,
    targetGoldSec: 64,
    targetSilverSec: 70,
    targetBronzeSec: 78,
    trafficDensity: 0.48,
    oncomingProbability: 0.35,
    theme: 'downtown',
    rewardCash: 5500,
    rewardRep: 450,
  },
  {
    id: 'track_08',
    name: 'Мост над бездной: Огни высоток',
    district: 'Неоновый Даунтаун',
    districtId: 3,
    lengthMeters: 2800,
    baseTimeLimitSec: 82,
    targetGoldSec: 67,
    targetSilverSec: 74,
    targetBronzeSec: 82,
    trafficDensity: 0.50,
    oncomingProbability: 0.38,
    theme: 'bridge',
    rewardCash: 6000,
    rewardRep: 500,
  },
  {
    id: 'track_09',
    name: 'Золотая миля: Ночной дождь',
    district: 'Неоновый Даунтаун',
    districtId: 3,
    lengthMeters: 3000,
    baseTimeLimitSec: 88,
    targetGoldSec: 72,
    targetSilverSec: 79,
    targetBronzeSec: 88,
    trafficDensity: 0.52,
    oncomingProbability: 0.40,
    theme: 'downtown',
    rewardCash: 7000,
    rewardRep: 550,
  },

  // District 4: Индустриальная эстакада (Apex Speedway)
  {
    id: 'track_10',
    name: 'Скоростная развязка: Овердрайв',
    district: 'Индустриальная эстакада',
    districtId: 4,
    lengthMeters: 2800,
    baseTimeLimitSec: 80,
    targetGoldSec: 65,
    targetSilverSec: 72,
    targetBronzeSec: 80,
    trafficDensity: 0.55,
    oncomingProbability: 0.42,
    theme: 'highway',
    rewardCash: 8000,
    rewardRep: 650,
  },
  {
    id: 'track_11',
    name: 'Аллея бритвы: Встречный ад',
    district: 'Индустриальная эстакада',
    districtId: 4,
    lengthMeters: 3000,
    baseTimeLimitSec: 85,
    targetGoldSec: 69,
    targetSilverSec: 76,
    targetBronzeSec: 85,
    trafficDensity: 0.60,
    oncomingProbability: 0.45,
    theme: 'downtown',
    rewardCash: 10000,
    rewardRep: 750,
  },
  {
    id: 'track_12',
    name: 'Королевский спринт: Финал лиги',
    district: 'Индустриальная эстакада',
    districtId: 4,
    lengthMeters: 3300,
    baseTimeLimitSec: 90,
    targetGoldSec: 74,
    targetSilverSec: 81,
    targetBronzeSec: 90,
    trafficDensity: 0.65,
    oncomingProbability: 0.48,
    theme: 'bridge',
    rewardCash: 15000,
    rewardRep: 1000,
  },
];

export const UPGRADE_PRICES = {
  engine: [0, 3000, 8000, 20000],
  nitro: [0, 2500, 7000],
  handling: [0, 2000, 6000],
  weight: [0, 3500, 9000],
};

export const COLOR_OPTIONS = [
  '#ffffff',
  '#111111',
  '#ff073a',
  '#00f0ff',
  '#7928ca',
  '#ffd700',
  '#00ff66',
  '#ff007f',
];

export const NEON_OPTIONS = [
  '#00f0ff',
  '#ff007f',
  '#7928ca',
  '#00ff66',
  '#ffd700',
  '#ff073a',
];

export const DEFAULT_SAVE_DATA: PlayerSaveData = {
  cash: 5000,
  rep: 0,
  unlockedCars: ['car_hatch_s'],
  selectedCarId: 'car_hatch_s',
  carUpgrades: {
    car_hatch_s: { engineStage: 1, nitroStage: 1, handlingStage: 1, weightStage: 1, bodyColor: '#ffffff', neonColor: '#00f0ff' },
    car_drift_s13: { engineStage: 1, nitroStage: 1, handlingStage: 1, weightStage: 1, bodyColor: '#7928ca', neonColor: '#ff007f' },
    car_muscle_gt: { engineStage: 1, nitroStage: 1, handlingStage: 1, weightStage: 1, bodyColor: '#d4af37', neonColor: '#ffd700' },
    car_super_v10: { engineStage: 1, nitroStage: 1, handlingStage: 1, weightStage: 1, bodyColor: '#00f0ff', neonColor: '#00f0ff' },
    car_apex_gtr: { engineStage: 1, nitroStage: 1, handlingStage: 1, weightStage: 1, bodyColor: '#ff073a', neonColor: '#ff073a' },
    car_hyper_phantom: { engineStage: 1, nitroStage: 1, handlingStage: 1, weightStage: 1, bodyColor: '#2979ff', neonColor: '#7928ca' },
  },
  trackRecords: {},
  settings: {
    musicVolume: 0.7,
    sfxVolume: 0.85,
    graphicsQuality: 'high',
    touchScheme: 'drag_and_buttons',
    language: 'ru',
  },
  vipAdFree: false,
  lastDailyRewardTime: 0,
};