import { LevelConfig } from '../types/game';

export interface ChapterInfo {
  chapter: number;
  nameRu: string;
  subtitleRu: string;
  descriptionRu: string;
  biome: string;
  icon: string;
  startLevel: number;
  endLevel: number;
}

export const CHAPTERS: ChapterInfo[] = [
  {
    chapter: 1,
    nameRu: 'Окраины Пустоши',
    subtitleRu: 'Песчаный рубеж',
    descriptionRu: 'Первая линия обороны среди песчаных барханов и обломков цивилизации. Разведка боем.',
    biome: 'OUTSKIRTS',
    icon: '🏜️',
    startLevel: 1,
    endLevel: 10,
  },
  {
    chapter: 2,
    nameRu: 'Заброшенные Ангары',
    subtitleRu: 'Промзона смерти',
    descriptionRu: 'Индустриальные склады и цеха, кишащие быстрыми стаями бегунов и засадами мутантов.',
    biome: 'INDUSTRIAL',
    icon: '🏭',
    startLevel: 11,
    endLevel: 20,
  },
  {
    chapter: 3,
    nameRu: 'Токсичный Могильник',
    subtitleRu: 'Кислотная трясина',
    descriptionRu: 'Зона экологической катастрофы. Плевальщики заливают асфальт разъедающей кислотой.',
    biome: 'TOXIC',
    icon: '☣️',
    startLevel: 21,
    endLevel: 30,
  },
  {
    chapter: 4,
    nameRu: 'Нефтяной Завод',
    subtitleRu: 'Огненный ад',
    descriptionRu: 'Крупнейший перерабатывающий комплекс. Взрывоопасные резервуары и бронированные бруты.',
    biome: 'REFINERY',
    icon: '🔥',
    startLevel: 31,
    endLevel: 40,
  },
  {
    chapter: 5,
    nameRu: 'Стальной Лабиринт',
    subtitleRu: 'Ночной дрифт',
    descriptionRu: 'Ночной рейд через гигантский терминал морских контейнеров. Узкие повороты и слепящий неон.',
    biome: 'NIGHT_NEON',
    icon: '🌃',
    startLevel: 41,
    endLevel: 50,
  },
  {
    chapter: 6,
    nameRu: 'Шоссе Безумия',
    subtitleRu: 'Песчаный шторм',
    descriptionRu: 'Скоростное шоссе сквозь бушующую песчаную бурю. Сверхскоростные полчища зараженных.',
    biome: 'DUST_STORM',
    icon: '🌪️',
    startLevel: 51,
    endLevel: 60,
  },
  {
    chapter: 7,
    nameRu: 'Кровавый Кратер',
    subtitleRu: 'Багровый рассвет',
    descriptionRu: 'Место падения метеорита с агрессивным вирусом. Мутанты приобрели нечеловеческую стойкость.',
    biome: 'CRIMSON',
    icon: '🩸',
    startLevel: 61,
    endLevel: 70,
  },
  {
    chapter: 8,
    nameRu: 'Ядерный Полигон',
    subtitleRu: 'Пепел и радиация',
    descriptionRu: 'Забытая военная база под слоем радиоактивного пепла. Свирепые бронированные гиганты.',
    biome: 'NUCLEAR_ASH',
    icon: '☢️',
    startLevel: 71,
    endLevel: 80,
  },
  {
    chapter: 9,
    nameRu: 'Пекло Титанов',
    subtitleRu: 'Лавовый разлом',
    descriptionRu: 'Раскаленные пустоши у магматического разлома. Орды титанов и сдвоенные боссы.',
    biome: 'INFERNAL',
    icon: '🌋',
    startLevel: 81,
    endLevel: 90,
  },
  {
    chapter: 10,
    nameRu: 'Апокалипсис',
    subtitleRu: 'Финальный рубеж',
    descriptionRu: 'Затмение солнца. Эпическая битва за будущее человечества против Владыки Апокалипсиса.',
    biome: 'APOCALYPSE',
    icon: '⚡',
    startLevel: 91,
    endLevel: 100,
  },
];

// Helper to generate and return all 100 levels
function generateCampaignLevels(): LevelConfig[] {
  const levels: LevelConfig[] = [
    // ═════════════════════════════════════════════════════════════════════
    // ГЛАВА 1: Окраины Пустоши (Уровни 1–10)
    // ═════════════════════════════════════════════════════════════════════
    {
      id: 1,
      chapter: 1,
      chapterNameRu: 'Окраины Пустоши',
      nameRu: 'Песчаный Дозор',
      subtitleRu: 'Разведка боем',
      descriptionRu: 'Первое боевое крещение. Опробуйте управление, входите в занос и тараньте бродячих ходоков.',
      totalWaves: 3,
      waveDuration: 30,
      hpMultiplier: 1.0,
      speedMultiplier: 1.0,
      countMultiplier: 1.0,
      rewardScrap: 120,
      targetKills: 25,
      minHealthPercentStar: 50,
      biome: 'OUTSKIRTS',
    },
    {
      id: 2,
      chapter: 1,
      chapterNameRu: 'Окраины Пустоши',
      nameRu: 'Ржавый Перекресток',
      subtitleRu: 'Первая кровь',
      descriptionRu: 'Ходоки собираются на развилке дорог. Набирайте скорость и сбивайте толпы бампером.',
      totalWaves: 3,
      waveDuration: 32,
      hpMultiplier: 1.03,
      speedMultiplier: 1.02,
      countMultiplier: 1.08,
      rewardScrap: 140,
      targetKills: 32,
      minHealthPercentStar: 50,
      biome: 'OUTSKIRTS',
    },
    {
      id: 3,
      chapter: 1,
      chapterNameRu: 'Окраины Пустоши',
      nameRu: 'Охота на Бегунов',
      subtitleRu: 'Быстрая реакция',
      descriptionRu: 'Среди песчаных холмов замечены стремительные бегуны. Копите нитро для резких уклонений.',
      totalWaves: 3,
      waveDuration: 34,
      hpMultiplier: 1.06,
      speedMultiplier: 1.04,
      countMultiplier: 1.15,
      rewardScrap: 160,
      targetKills: 40,
      minHealthPercentStar: 55,
      biome: 'OUTSKIRTS',
    },
    {
      id: 4,
      chapter: 1,
      chapterNameRu: 'Окраины Пустоши',
      nameRu: 'Засада у Заправки',
      subtitleRu: 'Взрывной маневр',
      descriptionRu: 'Используйте стоящие у дороги взрывные бочки, чтобы расчищать плотные кольца врагов.',
      totalWaves: 3,
      waveDuration: 35,
      hpMultiplier: 1.09,
      speedMultiplier: 1.05,
      countMultiplier: 1.22,
      rewardScrap: 190,
      targetKills: 48,
      minHealthPercentStar: 55,
      biome: 'OUTSKIRTS',
    },
    {
      id: 5,
      chapter: 1,
      chapterNameRu: 'Окраины Пустоши',
      nameRu: 'Пробуждение Голиафа',
      subtitleRu: 'Первый босс',
      descriptionRu: 'Земля содрогается: на арену вырывается Голиаф Пожиратель! Держите дистанцию и стреляйте.',
      totalWaves: 4,
      waveDuration: 35,
      hpMultiplier: 1.12,
      speedMultiplier: 1.06,
      countMultiplier: 1.28,
      bossWave: 4,
      bossName: 'Голиаф Пожиратель',
      rewardScrap: 300,
      targetKills: 60,
      minHealthPercentStar: 50,
      biome: 'OUTSKIRTS',
    },
    {
      id: 6,
      chapter: 1,
      chapterNameRu: 'Окраины Пустоши',
      nameRu: 'Каменистое Ущелье',
      subtitleRu: 'Плотный строй',
      descriptionRu: 'В узком пространстве зомби наступают тесными рядами. Идеальное место для затяжного дрифта.',
      totalWaves: 3,
      waveDuration: 35,
      hpMultiplier: 1.15,
      speedMultiplier: 1.07,
      countMultiplier: 1.35,
      rewardScrap: 220,
      targetKills: 65,
      minHealthPercentStar: 55,
      biome: 'OUTSKIRTS',
    },
    {
      id: 7,
      chapter: 1,
      chapterNameRu: 'Окраины Пустоши',
      nameRu: 'Свалка Дизеля',
      subtitleRu: 'Опасные плевки',
      descriptionRu: 'Появление кислотных плевальщиков. Маневрируйте между лужами и уничтожайте стрелков первыми.',
      totalWaves: 3,
      waveDuration: 36,
      hpMultiplier: 1.18,
      speedMultiplier: 1.08,
      countMultiplier: 1.4,
      rewardScrap: 250,
      targetKills: 72,
      minHealthPercentStar: 55,
      biome: 'OUTSKIRTS',
    },
    {
      id: 8,
      chapter: 1,
      chapterNameRu: 'Окраины Пустоши',
      nameRu: 'Ночной Патруль',
      subtitleRu: 'Наступление тьмы',
      descriptionRu: 'Стаи бегунов активизируются. Не сбавляйте ход, чтобы машина не застряла в толпе.',
      totalWaves: 4,
      waveDuration: 36,
      hpMultiplier: 1.21,
      speedMultiplier: 1.09,
      countMultiplier: 1.46,
      rewardScrap: 280,
      targetKills: 80,
      minHealthPercentStar: 55,
      biome: 'OUTSKIRTS',
    },
    {
      id: 9,
      chapter: 1,
      chapterNameRu: 'Окраины Пустоши',
      nameRu: 'Штурм Окрестностей',
      subtitleRu: 'Волна за волной',
      descriptionRu: 'Четыре непрерывные волны с участием тяжелых брутов-громил. Тараньте только на полной скорости.',
      totalWaves: 4,
      waveDuration: 38,
      hpMultiplier: 1.24,
      speedMultiplier: 1.1,
      countMultiplier: 1.52,
      rewardScrap: 320,
      targetKills: 90,
      minHealthPercentStar: 55,
      biome: 'OUTSKIRTS',
    },
    {
      id: 10,
      chapter: 1,
      chapterNameRu: 'Окраины Пустоши',
      nameRu: 'Цитадель Песков',
      subtitleRu: 'Финал главы 1',
      descriptionRu: 'Финальный бой за окраины! Разъяренный Голиаф в сопровождении бронированных брутов.',
      totalWaves: 4,
      waveDuration: 40,
      hpMultiplier: 1.28,
      speedMultiplier: 1.12,
      countMultiplier: 1.6,
      bossWave: 4,
      bossName: 'Голиаф Песчаный Титан',
      rewardScrap: 500,
      targetKills: 105,
      minHealthPercentStar: 50,
      biome: 'OUTSKIRTS',
    },

    // ═════════════════════════════════════════════════════════════════════
    // ГЛАВА 2: Заброшенные Ангары (Уровни 11–20)
    // ═════════════════════════════════════════════════════════════════════
    {
      id: 11,
      chapter: 2,
      chapterNameRu: 'Заброшенные Ангары',
      nameRu: 'Въезд в Промзону',
      subtitleRu: 'Стальные ворота',
      descriptionRu: 'Мы вошли в сектор ангаров. Врагов стало больше, а коридоры стали теснее.',
      totalWaves: 3,
      waveDuration: 35,
      hpMultiplier: 1.32,
      speedMultiplier: 1.13,
      countMultiplier: 1.65,
      rewardScrap: 350,
      targetKills: 85,
      minHealthPercentStar: 55,
      biome: 'INDUSTRIAL',
    },
    {
      id: 12,
      chapter: 2,
      chapterNameRu: 'Заброшенные Ангары',
      nameRu: 'Сборочный Цех',
      subtitleRu: 'Ржавый конвейер',
      descriptionRu: 'Бегуны выскакивают из-за станков и станций. Используйте пилы и огнемет для зачистки.',
      totalWaves: 3,
      waveDuration: 36,
      hpMultiplier: 1.35,
      speedMultiplier: 1.14,
      countMultiplier: 1.7,
      rewardScrap: 380,
      targetKills: 92,
      minHealthPercentStar: 55,
      biome: 'INDUSTRIAL',
    },
    {
      id: 13,
      chapter: 2,
      chapterNameRu: 'Заброшенные Ангары',
      nameRu: 'Грузовой Слалом',
      subtitleRu: 'Дрифт между стеллажами',
      descriptionRu: 'Управляемый занос на 180° позволяет срезать углы и давить преследователей.',
      totalWaves: 4,
      waveDuration: 36,
      hpMultiplier: 1.38,
      speedMultiplier: 1.15,
      countMultiplier: 1.75,
      rewardScrap: 410,
      targetKills: 100,
      minHealthPercentStar: 55,
      biome: 'INDUSTRIAL',
    },
    {
      id: 14,
      chapter: 2,
      chapterNameRu: 'Заброшенные Ангары',
      nameRu: 'Резервуары Охлаждения',
      subtitleRu: 'Холодная сталь',
      descriptionRu: 'Массивные бруты блокируют проезды. Заряжайте нитро в дрифте и пробивайте строй.',
      totalWaves: 4,
      waveDuration: 37,
      hpMultiplier: 1.41,
      speedMultiplier: 1.16,
      countMultiplier: 1.8,
      rewardScrap: 440,
      targetKills: 110,
      minHealthPercentStar: 55,
      biome: 'INDUSTRIAL',
    },
    {
      id: 15,
      chapter: 2,
      chapterNameRu: 'Заброшенные Ангары',
      nameRu: 'Логово Дробителя',
      subtitleRu: 'Босс ангаров',
      descriptionRu: 'Стальной гигант Дробитель Костей крушит все на своем пути. Уворачивайтесь от мощных ударов в землю.',
      totalWaves: 4,
      waveDuration: 38,
      hpMultiplier: 1.45,
      speedMultiplier: 1.17,
      countMultiplier: 1.85,
      bossWave: 4,
      bossName: 'Дробитель Костей',
      rewardScrap: 600,
      targetKills: 120,
      minHealthPercentStar: 50,
      biome: 'INDUSTRIAL',
    },
    {
      id: 16,
      chapter: 2,
      chapterNameRu: 'Заброшенные Ангары',
      nameRu: 'Платформа Погрузки',
      subtitleRu: 'Тяжелый груз',
      descriptionRu: 'Увеличенная плотность плевальщиков. Стреляйте ракетами по скоплениям врагов.',
      totalWaves: 4,
      waveDuration: 38,
      hpMultiplier: 1.48,
      speedMultiplier: 1.18,
      countMultiplier: 1.9,
      rewardScrap: 470,
      targetKills: 125,
      minHealthPercentStar: 55,
      biome: 'INDUSTRIAL',
    },
    {
      id: 17,
      chapter: 2,
      chapterNameRu: 'Заброшенные Ангары',
      nameRu: 'Сталеплавильный Двор',
      subtitleRu: 'Жар металла',
      descriptionRu: 'Пять затяжных волн. Собирайте выпадающие из ящиков аптечки и шестеренки.',
      totalWaves: 5,
      waveDuration: 38,
      hpMultiplier: 1.52,
      speedMultiplier: 1.19,
      countMultiplier: 1.95,
      rewardScrap: 510,
      targetKills: 135,
      minHealthPercentStar: 55,
      biome: 'INDUSTRIAL',
    },
    {
      id: 18,
      chapter: 2,
      chapterNameRu: 'Заброшенные Ангары',
      nameRu: 'Эстакада Трубопровода',
      subtitleRu: 'Высокое давление',
      descriptionRu: 'Орда брутов и бегунов атакует с флангов. Держите скорость выше 18 м/с.',
      totalWaves: 4,
      waveDuration: 39,
      hpMultiplier: 1.55,
      speedMultiplier: 1.2,
      countMultiplier: 2.0,
      rewardScrap: 540,
      targetKills: 140,
      minHealthPercentStar: 55,
      biome: 'INDUSTRIAL',
    },
    {
      id: 19,
      chapter: 2,
      chapterNameRu: 'Заброшенные Ангары',
      nameRu: 'Главный Терминал',
      subtitleRu: 'Осадное положение',
      descriptionRu: 'Предельная концентрация мутантов перед командным комплексом.',
      totalWaves: 5,
      waveDuration: 40,
      hpMultiplier: 1.59,
      speedMultiplier: 1.21,
      countMultiplier: 2.05,
      rewardScrap: 580,
      targetKills: 150,
      minHealthPercentStar: 55,
      biome: 'INDUSTRIAL',
    },
    {
      id: 20,
      chapter: 2,
      chapterNameRu: 'Заброшенные Ангары',
      nameRu: 'Сердце Индустрии',
      subtitleRu: 'Финал главы 2',
      descriptionRu: 'Дробитель возвращается в яростной модификации! Уничтожьте его и расчистите путь к болотам.',
      totalWaves: 5,
      waveDuration: 40,
      hpMultiplier: 1.63,
      speedMultiplier: 1.22,
      countMultiplier: 2.1,
      bossWave: 5,
      bossName: 'Стальной Дробитель МК-2',
      rewardScrap: 800,
      targetKills: 165,
      minHealthPercentStar: 50,
      biome: 'INDUSTRIAL',
    },

    // ═════════════════════════════════════════════════════════════════════
    // ГЛАВА 3: Токсичный Могильник (Уровни 21–30)
    // ═════════════════════════════════════════════════════════════════════
    {
      id: 21,
      chapter: 3,
      chapterNameRu: 'Токсичный Могильник',
      nameRu: 'Зеленый Туман',
      subtitleRu: 'Химическая тревога',
      descriptionRu: 'Воздух пропитан едкими парами. Плевальщики стреляют чаще и с большего расстояния.',
      totalWaves: 4,
      waveDuration: 36,
      hpMultiplier: 1.67,
      speedMultiplier: 1.23,
      countMultiplier: 2.15,
      rewardScrap: 620,
      targetKills: 130,
      minHealthPercentStar: 55,
      biome: 'TOXIC',
    },
    {
      id: 22,
      chapter: 3,
      chapterNameRu: 'Токсичный Могильник',
      nameRu: 'Кислотные Озера',
      subtitleRu: 'Опасный дрифт',
      descriptionRu: 'Не наезжайте на зеленые лужи надолго — они наносят постоянный урон и замедляют колеса.',
      totalWaves: 4,
      waveDuration: 37,
      hpMultiplier: 1.7,
      speedMultiplier: 1.24,
      countMultiplier: 2.2,
      rewardScrap: 650,
      targetKills: 140,
      minHealthPercentStar: 55,
      biome: 'TOXIC',
    },
    {
      id: 23,
      chapter: 3,
      chapterNameRu: 'Токсичный Могильник',
      nameRu: 'Карантинная Зона',
      subtitleRu: 'Оцепление прорвано',
      descriptionRu: 'Огромные стаи зараженных вырываются из-под защитных куполов.',
      totalWaves: 4,
      waveDuration: 38,
      hpMultiplier: 1.74,
      speedMultiplier: 1.24,
      countMultiplier: 2.25,
      rewardScrap: 680,
      targetKills: 148,
      minHealthPercentStar: 55,
      biome: 'TOXIC',
    },
    {
      id: 24,
      chapter: 3,
      chapterNameRu: 'Токсичный Могильник',
      nameRu: 'Химлаборатория',
      subtitleRu: 'Мутагенные споры',
      descriptionRu: 'Ходоки стали более живучими под воздействием радиации. Используйте пулеметные турели.',
      totalWaves: 4,
      waveDuration: 38,
      hpMultiplier: 1.78,
      speedMultiplier: 1.25,
      countMultiplier: 2.3,
      rewardScrap: 720,
      targetKills: 155,
      minHealthPercentStar: 55,
      biome: 'TOXIC',
    },
    {
      id: 25,
      chapter: 3,
      chapterNameRu: 'Токсичный Могильник',
      nameRu: 'Болотный Бегемот',
      subtitleRu: 'Босс могильника',
      descriptionRu: 'Из глубин трясины поднимается Токсичный Бегемот, заливающий арену волнами кислоты!',
      totalWaves: 5,
      waveDuration: 39,
      hpMultiplier: 1.82,
      speedMultiplier: 1.26,
      countMultiplier: 2.35,
      bossWave: 5,
      bossName: 'Токсичный Бегемот',
      rewardScrap: 950,
      targetKills: 170,
      minHealthPercentStar: 50,
      biome: 'TOXIC',
    },
    {
      id: 26,
      chapter: 3,
      chapterNameRu: 'Токсичный Могильник',
      nameRu: 'Могильник Отходов',
      subtitleRu: 'Свалка биохазарда',
      descriptionRu: 'Мусорные горы и бочки с реактивами. Взрывайте бочки для массового уничтожения орд.',
      totalWaves: 4,
      waveDuration: 39,
      hpMultiplier: 1.86,
      speedMultiplier: 1.26,
      countMultiplier: 2.38,
      rewardScrap: 760,
      targetKills: 160,
      minHealthPercentStar: 55,
      biome: 'TOXIC',
    },
    {
      id: 27,
      chapter: 3,
      chapterNameRu: 'Токсичный Могильник',
      nameRu: 'Дренажный Коллектор',
      subtitleRu: 'Подземный прорыв',
      descriptionRu: 'Плотный спавн бегунов прямо перед капотом. Таран на форсаже — единственное спасение.',
      totalWaves: 4,
      waveDuration: 40,
      hpMultiplier: 1.9,
      speedMultiplier: 1.27,
      countMultiplier: 2.42,
      rewardScrap: 800,
      targetKills: 170,
      minHealthPercentStar: 55,
      biome: 'TOXIC',
    },
    {
      id: 28,
      chapter: 3,
      chapterNameRu: 'Токсичный Могильник',
      nameRu: 'Едкие Испарения',
      subtitleRu: 'Нулевая видимость',
      descriptionRu: 'Зеленый смог сгущается. Ориентируйтесь по мини-карте и индикаторам попаданий.',
      totalWaves: 5,
      waveDuration: 40,
      hpMultiplier: 1.94,
      speedMultiplier: 1.27,
      countMultiplier: 2.45,
      rewardScrap: 840,
      targetKills: 180,
      minHealthPercentStar: 55,
      biome: 'TOXIC',
    },
    {
      id: 29,
      chapter: 3,
      chapterNameRu: 'Токсичный Могильник',
      nameRu: 'Токсичный Разлом',
      subtitleRu: 'Преддверие ада',
      descriptionRu: 'Пять свирепых волн с максимальным числом плевальщиков и кислотных танков.',
      totalWaves: 5,
      waveDuration: 41,
      hpMultiplier: 1.98,
      speedMultiplier: 1.28,
      countMultiplier: 2.5,
      rewardScrap: 890,
      targetKills: 190,
      minHealthPercentStar: 55,
      biome: 'TOXIC',
    },
    {
      id: 30,
      chapter: 3,
      chapterNameRu: 'Токсичный Могильник',
      nameRu: 'Чумной Бастион',
      subtitleRu: 'Финал главы 3',
      descriptionRu: 'Финальный бой в токсичной зоне против Чумного Левиафана и его кислотной свиты!',
      totalWaves: 5,
      waveDuration: 42,
      hpMultiplier: 2.03,
      speedMultiplier: 1.29,
      countMultiplier: 2.55,
      bossWave: 5,
      bossName: 'Чумной Левиафан',
      rewardScrap: 1200,
      targetKills: 205,
      minHealthPercentStar: 50,
      biome: 'TOXIC',
    },

    // ═════════════════════════════════════════════════════════════════════
    // ГЛАВА 4: Нефтяной Завод (Уровни 31–40)
    // ═════════════════════════════════════════════════════════════════════
    {
      id: 31,
      chapter: 4,
      chapterNameRu: 'Нефтяной Завод',
      nameRu: 'Нефтяной Факел',
      subtitleRu: 'Запах бензина',
      descriptionRu: 'Мы на территории нефтеперерабатывающего гиганта. Море топлива и раскаленные трубы.',
      totalWaves: 4,
      waveDuration: 38,
      hpMultiplier: 2.07,
      speedMultiplier: 1.29,
      countMultiplier: 2.58,
      rewardScrap: 930,
      targetKills: 165,
      minHealthPercentStar: 55,
      biome: 'REFINERY',
    },
    {
      id: 32,
      chapter: 4,
      chapterNameRu: 'Нефтяной Завод',
      nameRu: 'Парк Цистерн',
      subtitleRu: 'Слалом взрывов',
      descriptionRu: 'Цепные взрывы бочек наносят колоссальный урон по площади. Заманивайте орды в ловушки.',
      totalWaves: 4,
      waveDuration: 38,
      hpMultiplier: 2.11,
      speedMultiplier: 1.3,
      countMultiplier: 2.6,
      rewardScrap: 970,
      targetKills: 175,
      minHealthPercentStar: 55,
      biome: 'REFINERY',
    },
    {
      id: 33,
      chapter: 4,
      chapterNameRu: 'Нефтяной Завод',
      nameRu: 'Крекинг-Колонна',
      subtitleRu: 'Давление растет',
      descriptionRu: 'Массивные бронированные бруты патрулируют эстакады. Прокачайте таранный бампер.',
      totalWaves: 4,
      waveDuration: 39,
      hpMultiplier: 2.15,
      speedMultiplier: 1.3,
      countMultiplier: 2.63,
      rewardScrap: 1020,
      targetKills: 185,
      minHealthPercentStar: 55,
      biome: 'REFINERY',
    },
    {
      id: 34,
      chapter: 4,
      chapterNameRu: 'Нефтяной Завод',
      nameRu: 'Мазутные Реки',
      subtitleRu: 'Скользкий асфальт',
      descriptionRu: 'Масляные пятна увеличивают угол дрифта. Копите нитро-ярость мгновенно.',
      totalWaves: 5,
      waveDuration: 39,
      hpMultiplier: 2.2,
      speedMultiplier: 1.31,
      countMultiplier: 2.66,
      rewardScrap: 1070,
      targetKills: 195,
      minHealthPercentStar: 55,
      biome: 'REFINERY',
    },
    {
      id: 35,
      chapter: 4,
      chapterNameRu: 'Нефтяной Завод',
      nameRu: 'Инферно-Титан',
      subtitleRu: 'Босс нефтебазы',
      descriptionRu: 'Огненный монстр Инферно-Титан с раскаленной броней выходит на дуэль!',
      totalWaves: 5,
      waveDuration: 40,
      hpMultiplier: 2.25,
      speedMultiplier: 1.32,
      countMultiplier: 2.7,
      bossWave: 5,
      bossName: 'Инферно-Титан',
      rewardScrap: 1400,
      targetKills: 215,
      minHealthPercentStar: 50,
      biome: 'REFINERY',
    },
    {
      id: 36,
      chapter: 4,
      chapterNameRu: 'Нефтяной Завод',
      nameRu: 'Насосная Станция',
      subtitleRu: 'Шквал огня',
      descriptionRu: 'Используйте огнеметы и миниганы против бесконечных орд зараженных рабочих.',
      totalWaves: 4,
      waveDuration: 40,
      hpMultiplier: 2.29,
      speedMultiplier: 1.32,
      countMultiplier: 2.72,
      rewardScrap: 1120,
      targetKills: 190,
      minHealthPercentStar: 55,
      biome: 'REFINERY',
    },
    {
      id: 37,
      chapter: 4,
      chapterNameRu: 'Нефтяной Завод',
      nameRu: 'Трубопроводный Мост',
      subtitleRu: 'Опасный коридор',
      descriptionRu: 'Узкий проезд не дает места для маневра. Сносите врагов прямым лобовым ударом.',
      totalWaves: 5,
      waveDuration: 40,
      hpMultiplier: 2.34,
      speedMultiplier: 1.33,
      countMultiplier: 2.75,
      rewardScrap: 1170,
      targetKills: 205,
      minHealthPercentStar: 55,
      biome: 'REFINERY',
    },
    {
      id: 38,
      chapter: 4,
      chapterNameRu: 'Нефтяной Завод',
      nameRu: 'Битумная Яма',
      subtitleRu: 'Вязкая ловушка',
      descriptionRu: 'Тяжелые бруты-громилы выходят двойками. Держите дистанцию стрельбы.',
      totalWaves: 5,
      waveDuration: 41,
      hpMultiplier: 2.39,
      speedMultiplier: 1.33,
      countMultiplier: 2.78,
      rewardScrap: 1220,
      targetKills: 215,
      minHealthPercentStar: 55,
      biome: 'REFINERY',
    },
    {
      id: 39,
      chapter: 4,
      chapterNameRu: 'Нефтяной Завод',
      nameRu: 'Огненный Котел',
      subtitleRu: 'Предел температуры',
      descriptionRu: 'Непрерывный штурм сотен врагов. Сбор шестеренок критически важен для выживания.',
      totalWaves: 5,
      waveDuration: 41,
      hpMultiplier: 2.44,
      speedMultiplier: 1.34,
      countMultiplier: 2.8,
      rewardScrap: 1280,
      targetKills: 225,
      minHealthPercentStar: 55,
      biome: 'REFINERY',
    },
    {
      id: 40,
      chapter: 4,
      chapterNameRu: 'Нефтяной Завод',
      nameRu: 'Вулкан Нефтебазы',
      subtitleRu: 'Финал главы 4',
      descriptionRu: 'Инферно-Колосс в огненой ярости! Победа откроет путь в ночной контейнерный терминал.',
      totalWaves: 6,
      waveDuration: 42,
      hpMultiplier: 2.5,
      speedMultiplier: 1.35,
      countMultiplier: 2.85,
      bossWave: 6,
      bossName: 'Инферно-Колосс Огня',
      rewardScrap: 1700,
      targetKills: 250,
      minHealthPercentStar: 50,
      biome: 'REFINERY',
    },

    // ═════════════════════════════════════════════════════════════════════
    // ГЛАВА 5: Стальной Лабиринт (Уровни 41–50)
    // ═════════════════════════════════════════════════════════════════════
    {
      id: 41,
      chapter: 5,
      chapterNameRu: 'Стальной Лабиринт',
      nameRu: 'Ночной Терминал',
      subtitleRu: 'Неоновые тени',
      descriptionRu: 'Полночь. Свет фар прорезает тьму контейнерных аллей. Враги прячутся за углами.',
      totalWaves: 4,
      waveDuration: 38,
      hpMultiplier: 2.54,
      speedMultiplier: 1.35,
      countMultiplier: 2.85,
      rewardScrap: 1330,
      targetKills: 195,
      minHealthPercentStar: 55,
      biome: 'NIGHT_NEON',
    },
    {
      id: 42,
      chapter: 5,
      chapterNameRu: 'Стальной Лабиринт',
      nameRu: 'Синий Квартал',
      subtitleRu: 'Стальные лабиринты',
      descriptionRu: 'Морские контейнеры в два яруса. Дрифтуйте вдоль стен для набора ярости.',
      totalWaves: 4,
      waveDuration: 39,
      hpMultiplier: 2.59,
      speedMultiplier: 1.36,
      countMultiplier: 2.88,
      rewardScrap: 1380,
      targetKills: 205,
      minHealthPercentStar: 55,
      biome: 'NIGHT_NEON',
    },
    {
      id: 43,
      chapter: 5,
      chapterNameRu: 'Стальной Лабиринт',
      nameRu: 'Угол 90 Градусов',
      subtitleRu: 'Острый поворот',
      descriptionRu: 'Резкие виражи на ручнике позволяют впечатывать зомби в металлические стенки.',
      totalWaves: 5,
      waveDuration: 39,
      hpMultiplier: 2.64,
      speedMultiplier: 1.36,
      countMultiplier: 2.9,
      rewardScrap: 1440,
      targetKills: 215,
      minHealthPercentStar: 55,
      biome: 'NIGHT_NEON',
    },
    {
      id: 44,
      chapter: 5,
      chapterNameRu: 'Стальной Лабиринт',
      nameRu: 'Кран Погрузчика',
      subtitleRu: 'Под подвесом',
      descriptionRu: 'Плевальщики заняли позиции на возвышенностях. Не стойте на одном месте.',
      totalWaves: 5,
      waveDuration: 40,
      hpMultiplier: 2.69,
      speedMultiplier: 1.37,
      countMultiplier: 2.92,
      rewardScrap: 1500,
      targetKills: 225,
      minHealthPercentStar: 55,
      biome: 'NIGHT_NEON',
    },
    {
      id: 45,
      chapter: 5,
      chapterNameRu: 'Стальной Лабиринт',
      nameRu: 'Железный Мясник',
      subtitleRu: 'Босс лабиринта',
      descriptionRu: 'Тяжеловооруженный киборг-зомби Железный Мясник выходит на охоту в ночи!',
      totalWaves: 5,
      waveDuration: 40,
      hpMultiplier: 2.75,
      speedMultiplier: 1.37,
      countMultiplier: 2.95,
      bossWave: 5,
      bossName: 'Железный Мясник',
      rewardScrap: 1950,
      targetKills: 245,
      minHealthPercentStar: 50,
      biome: 'NIGHT_NEON',
    },
    {
      id: 46,
      chapter: 5,
      chapterNameRu: 'Стальной Лабиринт',
      nameRu: 'Контейнерный Слалом',
      subtitleRu: 'Безумный дрифт',
      descriptionRu: 'Скоростной проезд между четырьмя рядами контейнеров на пределе сцепления.',
      totalWaves: 5,
      waveDuration: 40,
      hpMultiplier: 2.8,
      speedMultiplier: 1.38,
      countMultiplier: 2.98,
      rewardScrap: 1560,
      targetKills: 235,
      minHealthPercentStar: 55,
      biome: 'NIGHT_NEON',
    },
    {
      id: 47,
      chapter: 5,
      chapterNameRu: 'Стальной Лабиринт',
      nameRu: 'Темный Тупик',
      subtitleRu: 'Окружение',
      descriptionRu: 'Засада в глухом переулке! Включайте нитро и пробивайте стену из зомби.',
      totalWaves: 5,
      waveDuration: 41,
      hpMultiplier: 2.85,
      speedMultiplier: 1.38,
      countMultiplier: 3.0,
      rewardScrap: 1620,
      targetKills: 245,
      minHealthPercentStar: 55,
      biome: 'NIGHT_NEON',
    },
    {
      id: 48,
      chapter: 5,
      chapterNameRu: 'Стальной Лабиринт',
      nameRu: 'Ржавый Док',
      subtitleRu: 'У края бездны',
      descriptionRu: 'Огромные пачки мутантов всех видов. Балансируйте между атакой и обороной.',
      totalWaves: 5,
      waveDuration: 41,
      hpMultiplier: 2.9,
      speedMultiplier: 1.39,
      countMultiplier: 3.02,
      rewardScrap: 1680,
      targetKills: 255,
      minHealthPercentStar: 55,
      biome: 'NIGHT_NEON',
    },
    {
      id: 49,
      chapter: 5,
      chapterNameRu: 'Стальной Лабиринт',
      nameRu: 'Ночной Шторм',
      subtitleRu: 'Апогей тьмы',
      descriptionRu: 'Пять тяжелейших волн при поддержке элитных брутов с повышенной броней.',
      totalWaves: 5,
      waveDuration: 42,
      hpMultiplier: 2.95,
      speedMultiplier: 1.39,
      countMultiplier: 3.05,
      rewardScrap: 1750,
      targetKills: 265,
      minHealthPercentStar: 55,
      biome: 'NIGHT_NEON',
    },
    {
      id: 50,
      chapter: 5,
      chapterNameRu: 'Стальной Лабиринт',
      nameRu: 'Стальной Палач',
      subtitleRu: 'Финал главы 5',
      descriptionRu: 'Половина кампании пройдена! Битва со Стальным Палачом на центральной площади терминала.',
      totalWaves: 6,
      waveDuration: 43,
      hpMultiplier: 3.02,
      speedMultiplier: 1.4,
      countMultiplier: 3.1,
      bossWave: 6,
      bossName: 'Стальной Палач Ночи',
      rewardScrap: 2300,
      targetKills: 290,
      minHealthPercentStar: 50,
      biome: 'NIGHT_NEON',
    },

    // ═════════════════════════════════════════════════════════════════════
    // ГЛАВА 6: Шоссе Безумия (Уровни 51–60)
    // ═════════════════════════════════════════════════════════════════════
    {
      id: 51,
      chapter: 6,
      chapterNameRu: 'Шоссе Безумия',
      nameRu: 'Песчаная Буря',
      subtitleRu: 'Ветер ярости',
      descriptionRu: 'Бушующая пылевая буря. Скорость движения зомби возросла на 30%.',
      totalWaves: 4,
      waveDuration: 39,
      hpMultiplier: 3.07,
      speedMultiplier: 1.4,
      countMultiplier: 3.1,
      rewardScrap: 1820,
      targetKills: 220,
      minHealthPercentStar: 55,
      biome: 'DUST_STORM',
    },
    {
      id: 52,
      chapter: 6,
      chapterNameRu: 'Шоссе Безумия',
      nameRu: 'Скоростной Участок',
      subtitleRu: 'Газ в пол',
      descriptionRu: 'Прямые отрезки позволяют развить максимальную скорость. Тараньте стаи ходоков сходу.',
      totalWaves: 5,
      waveDuration: 39,
      hpMultiplier: 3.12,
      speedMultiplier: 1.41,
      countMultiplier: 3.12,
      rewardScrap: 1890,
      targetKills: 230,
      minHealthPercentStar: 55,
      biome: 'DUST_STORM',
    },
    {
      id: 53,
      chapter: 6,
      chapterNameRu: 'Шоссе Безумия',
      nameRu: 'Автострада Смерти',
      subtitleRu: 'Встречный поток',
      descriptionRu: 'Бегуны несутся прямо в лоб. Дрифт и боковой занос защитят от лобового урона.',
      totalWaves: 5,
      waveDuration: 40,
      hpMultiplier: 3.17,
      speedMultiplier: 1.41,
      countMultiplier: 3.15,
      rewardScrap: 1960,
      targetKills: 240,
      minHealthPercentStar: 55,
      biome: 'DUST_STORM',
    },
    {
      id: 54,
      chapter: 6,
      chapterNameRu: 'Шоссе Безумия',
      nameRu: 'Развязка Смертников',
      subtitleRu: 'Многоуровневый бой',
      descriptionRu: 'Круговое движение. Дрифтуйте по кольцу без остановки для максимального бонуса ярости.',
      totalWaves: 5,
      waveDuration: 40,
      hpMultiplier: 3.22,
      speedMultiplier: 1.42,
      countMultiplier: 3.18,
      rewardScrap: 2030,
      targetKills: 250,
      minHealthPercentStar: 55,
      biome: 'DUST_STORM',
    },
    {
      id: 55,
      chapter: 6,
      chapterNameRu: 'Шоссе Безумия',
      nameRu: 'Буревестник Смерти',
      subtitleRu: 'Босс бури',
      descriptionRu: 'Стремительный и свирепый Буревестник налетает сквозь песок на бешеной скорости!',
      totalWaves: 5,
      waveDuration: 41,
      hpMultiplier: 3.28,
      speedMultiplier: 1.43,
      countMultiplier: 3.2,
      bossWave: 5,
      bossName: 'Буревестник Смерти',
      rewardScrap: 2600,
      targetKills: 275,
      minHealthPercentStar: 50,
      biome: 'DUST_STORM',
    },
    {
      id: 56,
      chapter: 6,
      chapterNameRu: 'Шоссе Безумия',
      nameRu: 'Пылевой Вихрь',
      subtitleRu: 'В эпицентре',
      descriptionRu: 'Плотный рой мутантов. Ракетница и тесла-излучатель работают на пике эффективности.',
      totalWaves: 5,
      waveDuration: 41,
      hpMultiplier: 3.33,
      speedMultiplier: 1.43,
      countMultiplier: 3.22,
      rewardScrap: 2100,
      targetKills: 260,
      minHealthPercentStar: 55,
      biome: 'DUST_STORM',
    },
    {
      id: 57,
      chapter: 6,
      chapterNameRu: 'Шоссе Безумия',
      nameRu: 'Обрыв Каньона',
      subtitleRu: 'У края пропасти',
      descriptionRu: 'Не врезайтесь в ограждения — сохраняйте кинетическую энергию для тарана танков.',
      totalWaves: 5,
      waveDuration: 41,
      hpMultiplier: 3.38,
      speedMultiplier: 1.44,
      countMultiplier: 3.25,
      rewardScrap: 2180,
      targetKills: 270,
      minHealthPercentStar: 55,
      biome: 'DUST_STORM',
    },
    {
      id: 58,
      chapter: 6,
      chapterNameRu: 'Шоссе Безумия',
      nameRu: 'Шоссе 66',
      subtitleRu: 'Проклятая миля',
      descriptionRu: 'Огромная плотность бронированных врагов. Постоянный огонь турелей и шипы бампера.',
      totalWaves: 5,
      waveDuration: 42,
      hpMultiplier: 3.44,
      speedMultiplier: 1.44,
      countMultiplier: 3.28,
      rewardScrap: 2260,
      targetKills: 280,
      minHealthPercentStar: 55,
      biome: 'DUST_STORM',
    },
    {
      id: 59,
      chapter: 6,
      chapterNameRu: 'Шоссе Безумия',
      nameRu: 'Ураганная Гряда',
      subtitleRu: 'Последний рубеж шоссе',
      descriptionRu: 'Шесть мощных волн перед выходом к кровавому метеоритному кратеру.',
      totalWaves: 6,
      waveDuration: 42,
      hpMultiplier: 3.5,
      speedMultiplier: 1.45,
      countMultiplier: 3.3,
      rewardScrap: 2350,
      targetKills: 295,
      minHealthPercentStar: 55,
      biome: 'DUST_STORM',
    },
    {
      id: 60,
      chapter: 6,
      chapterNameRu: 'Шоссе Безумия',
      nameRu: 'Владыка Бури',
      subtitleRu: 'Финал главы 6',
      descriptionRu: 'Буревестник-Император и его свита брутов. Продемонстрируйте высший класс дрифта!',
      totalWaves: 6,
      waveDuration: 43,
      hpMultiplier: 3.56,
      speedMultiplier: 1.45,
      countMultiplier: 3.35,
      bossWave: 6,
      bossName: 'Буревестник-Император',
      rewardScrap: 3000,
      targetKills: 320,
      minHealthPercentStar: 50,
      biome: 'DUST_STORM',
    },

    // ═════════════════════════════════════════════════════════════════════
    // ГЛАВА 7: Кровавый Кратер (Уровни 61–70)
    // ═════════════════════════════════════════════════════════════════════
    {
      id: 61,
      chapter: 7,
      chapterNameRu: 'Кровавый Кратер',
      nameRu: 'Багровый Горизонт',
      subtitleRu: 'Кровавая земля',
      descriptionRu: 'Земля окрашена в багровый цвет. Мутанты здесь быстрее, свирепее и сильнее.',
      totalWaves: 5,
      waveDuration: 40,
      hpMultiplier: 3.62,
      speedMultiplier: 1.45,
      countMultiplier: 3.35,
      rewardScrap: 2450,
      targetKills: 260,
      minHealthPercentStar: 55,
      biome: 'CRIMSON',
    },
    {
      id: 62,
      chapter: 7,
      chapterNameRu: 'Кровавый Кратер',
      nameRu: 'Осколки Метеорита',
      subtitleRu: 'Инопланетная зараза',
      descriptionRu: 'Красные кристаллы усиливают ярость зомби. Сбивайте их до того, как они окружат машину.',
      totalWaves: 5,
      waveDuration: 40,
      hpMultiplier: 3.68,
      speedMultiplier: 1.46,
      countMultiplier: 3.38,
      rewardScrap: 2550,
      targetKills: 270,
      minHealthPercentStar: 55,
      biome: 'CRIMSON',
    },
    {
      id: 63,
      chapter: 7,
      chapterNameRu: 'Кровавый Кратер',
      nameRu: 'Красное Озеро',
      subtitleRu: 'Багровые волны',
      descriptionRu: 'Огромные волны плевальщиков стреляют ядовитыми сгустками. Маневр "восьмерка" спасает жизнь.',
      totalWaves: 5,
      waveDuration: 41,
      hpMultiplier: 3.74,
      speedMultiplier: 1.46,
      countMultiplier: 3.4,
      rewardScrap: 2650,
      targetKills: 280,
      minHealthPercentStar: 55,
      biome: 'CRIMSON',
    },
    {
      id: 64,
      chapter: 7,
      chapterNameRu: 'Кровавый Кратер',
      nameRu: 'Разлом Судьбы',
      subtitleRu: 'Земля трещит',
      descriptionRu: 'Бруты наступают клином. Используйте ракетные залпы и взрывы бочек для разрыва строя.',
      totalWaves: 5,
      waveDuration: 41,
      hpMultiplier: 3.8,
      speedMultiplier: 1.47,
      countMultiplier: 3.42,
      rewardScrap: 2750,
      targetKills: 290,
      minHealthPercentStar: 55,
      biome: 'CRIMSON',
    },
    {
      id: 65,
      chapter: 7,
      chapterNameRu: 'Кровавый Кратер',
      nameRu: 'Кровавый Жнец',
      subtitleRu: 'Босс кратера',
      descriptionRu: 'Кровавый Жнец — колосс с сокрушительными ударами и бешеной скоростью бега!',
      totalWaves: 6,
      waveDuration: 42,
      hpMultiplier: 3.87,
      speedMultiplier: 1.47,
      countMultiplier: 3.45,
      bossWave: 6,
      bossName: 'Кровавый Жнец',
      rewardScrap: 3500,
      targetKills: 315,
      minHealthPercentStar: 50,
      biome: 'CRIMSON',
    },
    {
      id: 66,
      chapter: 7,
      chapterNameRu: 'Кровавый Кратер',
      nameRu: 'Алтарь Мутантов',
      subtitleRu: 'Древнее зло',
      descriptionRu: 'Бегуны окружают броневик кольцом. Дрифт на 360° расчищает пространство вокруг.',
      totalWaves: 5,
      waveDuration: 42,
      hpMultiplier: 3.93,
      speedMultiplier: 1.48,
      countMultiplier: 3.48,
      rewardScrap: 2850,
      targetKills: 295,
      minHealthPercentStar: 55,
      biome: 'CRIMSON',
    },
    {
      id: 67,
      chapter: 7,
      chapterNameRu: 'Кровавый Кратер',
      nameRu: 'Багровый Шквал',
      subtitleRu: 'Ярость орды',
      descriptionRu: 'Огромное количество выпадающих шестеренок. Своевременно подбирайте ресурсы магнитом.',
      totalWaves: 5,
      waveDuration: 42,
      hpMultiplier: 4.0,
      speedMultiplier: 1.48,
      countMultiplier: 3.5,
      rewardScrap: 2950,
      targetKills: 305,
      minHealthPercentStar: 55,
      biome: 'CRIMSON',
    },
    {
      id: 68,
      chapter: 7,
      chapterNameRu: 'Кровавый Кратер',
      nameRu: 'Пепел и Кости',
      subtitleRu: 'Мертвая зона',
      descriptionRu: 'Шесть тяжелых волн. Прокачайте прочность кузова и форсирование ДВС до предела.',
      totalWaves: 6,
      waveDuration: 43,
      hpMultiplier: 4.06,
      speedMultiplier: 1.49,
      countMultiplier: 3.52,
      rewardScrap: 3080,
      targetKills: 320,
      minHealthPercentStar: 55,
      biome: 'CRIMSON',
    },
    {
      id: 69,
      chapter: 7,
      chapterNameRu: 'Кровавый Кратер',
      nameRu: 'Врата Кратера',
      subtitleRu: 'Штурм цитадели',
      descriptionRu: 'Сотни мутантов атакуют со всех сторон. Ни одной секунды без стрельбы и тарана.',
      totalWaves: 6,
      waveDuration: 43,
      hpMultiplier: 4.13,
      speedMultiplier: 1.49,
      countMultiplier: 3.55,
      rewardScrap: 3200,
      targetKills: 335,
      minHealthPercentStar: 55,
      biome: 'CRIMSON',
    },
    {
      id: 70,
      chapter: 7,
      chapterNameRu: 'Кровавый Кратер',
      nameRu: 'Архидемон Кратера',
      subtitleRu: 'Финал главы 7',
      descriptionRu: 'Архидемон Кровавых Пустошей! Финальная битва седьмой зоны за выживание человечества.',
      totalWaves: 6,
      waveDuration: 44,
      hpMultiplier: 4.2,
      speedMultiplier: 1.5,
      countMultiplier: 3.6,
      bossWave: 6,
      bossName: 'Архидемон Кратера',
      rewardScrap: 4000,
      targetKills: 360,
      minHealthPercentStar: 50,
      biome: 'CRIMSON',
    },

    // ═════════════════════════════════════════════════════════════════════
    // ГЛАВА 8: Ядерный Полигон (Уровни 71–80)
    // ═════════════════════════════════════════════════════════════════════
    {
      id: 71,
      chapter: 8,
      chapterNameRu: 'Ядерный Полигон',
      nameRu: 'Радиоактивный Пепел',
      subtitleRu: 'Холодное безмолвие',
      descriptionRu: 'Пепел падает с серого неба. Мутанты закованны в радиоактивную броню.',
      totalWaves: 5,
      waveDuration: 41,
      hpMultiplier: 4.27,
      speedMultiplier: 1.5,
      countMultiplier: 3.6,
      rewardScrap: 3350,
      targetKills: 290,
      minHealthPercentStar: 55,
      biome: 'NUCLEAR_ASH',
    },
    {
      id: 72,
      chapter: 8,
      chapterNameRu: 'Ядерный Полигон',
      nameRu: 'Бункер 101',
      subtitleRu: 'Забытое оружие',
      descriptionRu: 'Среди заброшенных ракетных шахт бродят тяжелые мутанты. Таран наносит максимум урона в заносе.',
      totalWaves: 5,
      waveDuration: 41,
      hpMultiplier: 4.34,
      speedMultiplier: 1.51,
      countMultiplier: 3.63,
      rewardScrap: 3480,
      targetKills: 300,
      minHealthPercentStar: 55,
      biome: 'NUCLEAR_ASH',
    },
    {
      id: 73,
      chapter: 8,
      chapterNameRu: 'Ядерный Полигон',
      nameRu: 'Шахта Запуска',
      subtitleRu: 'Радиационный фон',
      descriptionRu: 'Огромные скопления брутов. Подбирайте ремонтные наборы для поддержания брони.',
      totalWaves: 5,
      waveDuration: 42,
      hpMultiplier: 4.41,
      speedMultiplier: 1.51,
      countMultiplier: 3.66,
      rewardScrap: 3600,
      targetKills: 310,
      minHealthPercentStar: 55,
      biome: 'NUCLEAR_ASH',
    },
    {
      id: 74,
      chapter: 8,
      chapterNameRu: 'Ядерный Полигон',
      nameRu: 'Полигон Испытаний',
      subtitleRu: 'Эпицентр взрыва',
      descriptionRu: 'Свирепый напор мутантов. Применяйте огнемет и теслу для массового контроля поля.',
      totalWaves: 6,
      waveDuration: 42,
      hpMultiplier: 4.48,
      speedMultiplier: 1.52,
      countMultiplier: 3.68,
      rewardScrap: 3750,
      targetKills: 325,
      minHealthPercentStar: 55,
      biome: 'NUCLEAR_ASH',
    },
    {
      id: 75,
      chapter: 8,
      chapterNameRu: 'Ядерный Полигон',
      nameRu: 'Радиоактивный Колосс',
      subtitleRu: 'Босс полигона',
      descriptionRu: 'Колосс, вобравший ядерную энергию. Его удары создают разрушительные ударные волны!',
      totalWaves: 6,
      waveDuration: 43,
      hpMultiplier: 4.56,
      speedMultiplier: 1.52,
      countMultiplier: 3.7,
      bossWave: 6,
      bossName: 'Радиоактивный Колосс',
      rewardScrap: 4500,
      targetKills: 350,
      minHealthPercentStar: 50,
      biome: 'NUCLEAR_ASH',
    },
    {
      id: 76,
      chapter: 8,
      chapterNameRu: 'Ядерный Полигон',
      nameRu: 'Мертвый Город',
      subtitleRu: 'Руины военных',
      descriptionRu: 'Улицы разрушенного городка. Узкие проезды требуют ювелирного контроля заноса.',
      totalWaves: 5,
      waveDuration: 42,
      hpMultiplier: 4.63,
      speedMultiplier: 1.53,
      countMultiplier: 3.72,
      rewardScrap: 3900,
      targetKills: 320,
      minHealthPercentStar: 55,
      biome: 'NUCLEAR_ASH',
    },
    {
      id: 77,
      chapter: 8,
      chapterNameRu: 'Ядерный Полигон',
      nameRu: 'Саркофаг Реактора',
      subtitleRu: 'Критическая масса',
      descriptionRu: 'Орда зомби наступает сплошной стеной. Используйте нитро для сокрушительных прорывов.',
      totalWaves: 6,
      waveDuration: 43,
      hpMultiplier: 4.7,
      speedMultiplier: 1.53,
      countMultiplier: 3.75,
      rewardScrap: 4050,
      targetKills: 335,
      minHealthPercentStar: 55,
      biome: 'NUCLEAR_ASH',
    },
    {
      id: 78,
      chapter: 8,
      chapterNameRu: 'Ядерный Полигон',
      nameRu: 'Радарная Станция',
      subtitleRu: 'Сигнал бедствия',
      descriptionRu: 'Семь затяжных волн непрерывного натиска. Проверьте свою выносливость.',
      totalWaves: 6,
      waveDuration: 43,
      hpMultiplier: 4.78,
      speedMultiplier: 1.54,
      countMultiplier: 3.78,
      rewardScrap: 4200,
      targetKills: 350,
      minHealthPercentStar: 55,
      biome: 'NUCLEAR_ASH',
    },
    {
      id: 79,
      chapter: 8,
      chapterNameRu: 'Ядерный Полигон',
      nameRu: 'Зона Отчуждения',
      subtitleRu: 'Предел радиации',
      descriptionRu: 'Преддверие адского магматического разлома. Врагов бесчисленное множество.',
      totalWaves: 6,
      waveDuration: 44,
      hpMultiplier: 4.86,
      speedMultiplier: 1.54,
      countMultiplier: 3.8,
      rewardScrap: 4400,
      targetKills: 365,
      minHealthPercentStar: 55,
      biome: 'NUCLEAR_ASH',
    },
    {
      id: 80,
      chapter: 8,
      chapterNameRu: 'Ядерный Полигон',
      nameRu: 'Атомный Дробитель',
      subtitleRu: 'Финал главы 8',
      descriptionRu: 'Атомный Дробитель с ядерным ядром! Одолейте гиганта и откройте доступ в Пекло Титанов.',
      totalWaves: 6,
      waveDuration: 45,
      hpMultiplier: 4.95,
      speedMultiplier: 1.55,
      countMultiplier: 3.85,
      bossWave: 6,
      bossName: 'Атомный Дробитель Смерти',
      rewardScrap: 5200,
      targetKills: 390,
      minHealthPercentStar: 50,
      biome: 'NUCLEAR_ASH',
    },

    // ═════════════════════════════════════════════════════════════════════
    // ГЛАВА 9: Пекло Титанов (Уровни 81–90)
    // ═════════════════════════════════════════════════════════════════════
    {
      id: 81,
      chapter: 9,
      chapterNameRu: 'Пекло Титанов',
      nameRu: 'Магматический Разлом',
      subtitleRu: 'Жидкий огонь',
      descriptionRu: 'Раскаленная лава и клубы дыма. Враги наносят двойной урон при медленной езде.',
      totalWaves: 5,
      waveDuration: 42,
      hpMultiplier: 5.03,
      speedMultiplier: 1.55,
      countMultiplier: 3.85,
      rewardScrap: 4600,
      targetKills: 330,
      minHealthPercentStar: 55,
      biome: 'INFERNAL',
    },
    {
      id: 82,
      chapter: 9,
      chapterNameRu: 'Пекло Титанов',
      nameRu: 'Лавовый Мост',
      subtitleRu: 'Дорога над бездной',
      descriptionRu: 'Удерживайте машину в заносе, нарезая круги и сжигая толпы огнеметом.',
      totalWaves: 6,
      waveDuration: 42,
      hpMultiplier: 5.12,
      speedMultiplier: 1.56,
      countMultiplier: 3.88,
      rewardScrap: 4800,
      targetKills: 345,
      minHealthPercentStar: 55,
      biome: 'INFERNAL',
    },
    {
      id: 83,
      chapter: 9,
      chapterNameRu: 'Пекло Титанов',
      nameRu: 'Пещера Вулкана',
      subtitleRu: 'Подземный ад',
      descriptionRu: 'Бегуны атакуют со скоростью молнии. Не отпускайте педаль газа ни на секунду.',
      totalWaves: 6,
      waveDuration: 43,
      hpMultiplier: 5.21,
      speedMultiplier: 1.56,
      countMultiplier: 3.9,
      rewardScrap: 5000,
      targetKills: 360,
      minHealthPercentStar: 55,
      biome: 'INFERNAL',
    },
    {
      id: 84,
      chapter: 9,
      chapterNameRu: 'Пекло Титанов',
      nameRu: 'Огненная Арена',
      subtitleRu: 'Гладиаторский бой',
      descriptionRu: 'Массивный спавн брутов-громил. Тараньте только при полном множителе дрифт-ярости.',
      totalWaves: 6,
      waveDuration: 43,
      hpMultiplier: 5.3,
      speedMultiplier: 1.57,
      countMultiplier: 3.92,
      rewardScrap: 5250,
      targetKills: 375,
      minHealthPercentStar: 55,
      biome: 'INFERNAL',
    },
    {
      id: 85,
      chapter: 9,
      chapterNameRu: 'Пекло Титанов',
      nameRu: 'Повелитель Пепла',
      subtitleRu: 'Босс пекла',
      descriptionRu: 'Повелитель Пепла — огнедышащий титан с чудовищным запасом здоровья и яростным чарджем!',
      totalWaves: 6,
      waveDuration: 44,
      hpMultiplier: 5.4,
      speedMultiplier: 1.57,
      countMultiplier: 3.95,
      bossWave: 6,
      bossName: 'Повелитель Пепла',
      rewardScrap: 6000,
      targetKills: 410,
      minHealthPercentStar: 50,
      biome: 'INFERNAL',
    },
    {
      id: 86,
      chapter: 9,
      chapterNameRu: 'Пекло Титанов',
      nameRu: 'Базальтовый Хребет',
      subtitleRu: 'Острые скалы',
      descriptionRu: 'Плотный шквал кислоты от элитных плевальщиков. Стреляйте ракетами на упреждение.',
      totalWaves: 6,
      waveDuration: 43,
      hpMultiplier: 5.49,
      speedMultiplier: 1.58,
      countMultiplier: 3.98,
      rewardScrap: 5500,
      targetKills: 385,
      minHealthPercentStar: 55,
      biome: 'INFERNAL',
    },
    {
      id: 87,
      chapter: 9,
      chapterNameRu: 'Пекло Титанов',
      nameRu: 'Огненный Смерч',
      subtitleRu: 'Пылающий вихрь',
      descriptionRu: 'Бесконечные волны ходоков и бегунов. Заряжайте нитро и жгите резину.',
      totalWaves: 6,
      waveDuration: 44,
      hpMultiplier: 5.58,
      speedMultiplier: 1.58,
      countMultiplier: 4.0,
      rewardScrap: 5800,
      targetKills: 400,
      minHealthPercentStar: 55,
      biome: 'INFERNAL',
    },
    {
      id: 88,
      chapter: 9,
      chapterNameRu: 'Пекло Титанов',
      nameRu: 'Трон Титанов',
      subtitleRu: 'Логово гигантов',
      descriptionRu: 'Семь свирепых волн с участием сильнейших элитных мутантов.',
      totalWaves: 7,
      waveDuration: 44,
      hpMultiplier: 5.68,
      speedMultiplier: 1.59,
      countMultiplier: 4.05,
      rewardScrap: 6100,
      targetKills: 430,
      minHealthPercentStar: 55,
      biome: 'INFERNAL',
    },
    {
      id: 89,
      chapter: 9,
      chapterNameRu: 'Пекло Титанов',
      nameRu: 'Врата Бездны',
      subtitleRu: 'Последний шаг к финалу',
      descriptionRu: 'Максимальный накал страстей. До финала кампании остался всего один шаг!',
      totalWaves: 7,
      waveDuration: 45,
      hpMultiplier: 5.78,
      speedMultiplier: 1.59,
      countMultiplier: 4.1,
      rewardScrap: 6500,
      targetKills: 450,
      minHealthPercentStar: 55,
      biome: 'INFERNAL',
    },
    {
      id: 90,
      chapter: 9,
      chapterNameRu: 'Пекло Титанов',
      nameRu: 'Владыка Пламени',
      subtitleRu: 'Финал главы 9',
      descriptionRu: 'Владыка Пламени выходит на решающий бой! Уничтожьте его и откройте Финальный Рубеж.',
      totalWaves: 7,
      waveDuration: 45,
      hpMultiplier: 5.9,
      speedMultiplier: 1.6,
      countMultiplier: 4.15,
      bossWave: 7,
      bossName: 'Владыка Пламени и Пепла',
      rewardScrap: 7500,
      targetKills: 480,
      minHealthPercentStar: 50,
      biome: 'INFERNAL',
    },

    // ═════════════════════════════════════════════════════════════════════
    // ГЛАВА 10: Апокалипсис (Уровни 91–100) — ФИНАЛЬНЫЙ РУБЕЖ
    // ═════════════════════════════════════════════════════════════════════
    {
      id: 91,
      chapter: 10,
      chapterNameRu: 'Апокалипсис',
      nameRu: 'Затмение Солнца',
      subtitleRu: 'Тьма опускается',
      descriptionRu: 'Солнце гаснет. Черное небо и кровавый диск. Начинается последняя битва за мир.',
      totalWaves: 6,
      waveDuration: 43,
      hpMultiplier: 6.0,
      speedMultiplier: 1.6,
      countMultiplier: 4.2,
      rewardScrap: 7000,
      targetKills: 420,
      minHealthPercentStar: 55,
      biome: 'APOCALYPSE',
    },
    {
      id: 92,
      chapter: 10,
      chapterNameRu: 'Апокалипсис',
      nameRu: 'Кольцо Огня',
      subtitleRu: 'Без права на ошибку',
      descriptionRu: 'Полчища мутантов атакуют плотнейшим строем. Только идеальный дрифт спасет жизнь.',
      totalWaves: 6,
      waveDuration: 43,
      hpMultiplier: 6.12,
      speedMultiplier: 1.61,
      countMultiplier: 4.25,
      rewardScrap: 7300,
      targetKills: 435,
      minHealthPercentStar: 55,
      biome: 'APOCALYPSE',
    },
    {
      id: 93,
      chapter: 10,
      chapterNameRu: 'Апокалипсис',
      nameRu: 'Багровый Рассвет',
      subtitleRu: 'Огонь всех орудий',
      descriptionRu: 'Все бортовые пушки, ракеты и пилы должны работать без пауз. Уничтожайте толпы.',
      totalWaves: 6,
      waveDuration: 44,
      hpMultiplier: 6.24,
      speedMultiplier: 1.61,
      countMultiplier: 4.3,
      rewardScrap: 7600,
      targetKills: 450,
      minHealthPercentStar: 55,
      biome: 'APOCALYPSE',
    },
    {
      id: 94,
      chapter: 10,
      chapterNameRu: 'Апокалипсис',
      nameRu: 'Штурм Цитадели Тьмы',
      subtitleRu: 'Прорыв блокады',
      descriptionRu: 'Орда брутов и плевальщиков. Используйте ускорители нитро и взрывы для расчистки пути.',
      totalWaves: 7,
      waveDuration: 44,
      hpMultiplier: 6.36,
      speedMultiplier: 1.62,
      countMultiplier: 4.35,
      rewardScrap: 8000,
      targetKills: 470,
      minHealthPercentStar: 55,
      biome: 'APOCALYPSE',
    },
    {
      id: 95,
      chapter: 10,
      chapterNameRu: 'Апокалипсис',
      nameRu: 'Предвестник Конца',
      subtitleRu: 'Полуфинальный босс',
      descriptionRu: 'Предвестник Апокалипсиса — исполин небывалой мощи. Уклоняйтесь от его сокрушительного рывка!',
      totalWaves: 7,
      waveDuration: 45,
      hpMultiplier: 6.5,
      speedMultiplier: 1.62,
      countMultiplier: 4.4,
      bossWave: 7,
      bossName: 'Предвестник Апокалипсиса',
      rewardScrap: 9000,
      targetKills: 500,
      minHealthPercentStar: 50,
      biome: 'APOCALYPSE',
    },
    {
      id: 96,
      chapter: 10,
      chapterNameRu: 'Апокалипсис',
      nameRu: 'Океан Крови',
      subtitleRu: 'Битва на истощение',
      descriptionRu: 'Семь затяжных волн непрерывного штурма. Никаких передышек, только чистая стальная ярость!',
      totalWaves: 7,
      waveDuration: 44,
      hpMultiplier: 6.62,
      speedMultiplier: 1.63,
      countMultiplier: 4.45,
      rewardScrap: 8500,
      targetKills: 485,
      minHealthPercentStar: 55,
      biome: 'APOCALYPSE',
    },
    {
      id: 97,
      chapter: 10,
      chapterNameRu: 'Апокалипсис',
      nameRu: 'Сердце Затмения',
      subtitleRu: 'Черная бездна',
      descriptionRu: 'Элитные мутанты максимального уровня. Прокачайте все модули гаража на максимум.',
      totalWaves: 7,
      waveDuration: 45,
      hpMultiplier: 6.75,
      speedMultiplier: 1.63,
      countMultiplier: 4.5,
      rewardScrap: 8900,
      targetKills: 505,
      minHealthPercentStar: 55,
      biome: 'APOCALYPSE',
    },
    {
      id: 98,
      chapter: 10,
      chapterNameRu: 'Апокалипсис',
      nameRu: 'Падение Небес',
      subtitleRu: 'Последние герои',
      descriptionRu: 'Земля раскалывается. Вы и ваша боевая машина — последняя надежда уцелевших людей.',
      totalWaves: 7,
      waveDuration: 45,
      hpMultiplier: 6.9,
      speedMultiplier: 1.64,
      countMultiplier: 4.55,
      rewardScrap: 9400,
      targetKills: 530,
      minHealthPercentStar: 55,
      biome: 'APOCALYPSE',
    },
    {
      id: 99,
      chapter: 10,
      chapterNameRu: 'Апокалипсис',
      nameRu: 'Врата в Вечность',
      subtitleRu: 'Канун финала',
      descriptionRu: 'Девяносто девятый рубеж! Орда максимальной плотности. Впереди главный бой всей вашей жизни.',
      totalWaves: 7,
      waveDuration: 45,
      hpMultiplier: 7.05,
      speedMultiplier: 1.64,
      countMultiplier: 4.6,
      rewardScrap: 10000,
      targetKills: 560,
      minHealthPercentStar: 55,
      biome: 'APOCALYPSE',
    },
    {
      id: 100,
      chapter: 10,
      chapterNameRu: 'Апокалипсис',
      nameRu: 'Владыка Апокалипсиса',
      subtitleRu: 'УЛЬТИМАТИВНЫЙ ФИНАЛ',
      descriptionRu: 'ФИНАЛЬНАЯ БИТВА ИГРЫ! Владыка Апокалипсиса во плоти! Победите его и станьте Абсолютной Легендой Пустоши!',
      totalWaves: 7,
      waveDuration: 46,
      hpMultiplier: 7.25,
      speedMultiplier: 1.65,
      countMultiplier: 4.7,
      bossWave: 7,
      bossName: 'ВЛАДЫКА АПОКАЛИПСИСА',
      rewardScrap: 25000,
      targetKills: 600,
      minHealthPercentStar: 45,
      biome: 'APOCALYPSE',
    },
  ];

  // Validate and sort by ID
  const uniqueLevels = new Map<number, LevelConfig>();
  levels.forEach((lvl) => {
    uniqueLevels.set(lvl.id, lvl);
  });

  const sorted = Array.from(uniqueLevels.values()).sort((a, b) => a.id - b.id);
  return sorted;
}

export const CAMPAIGN_LEVELS: LevelConfig[] = generateCampaignLevels();

export function getChapterInfo(chapter: number): ChapterInfo {
  return CHAPTERS.find((c) => c.chapter === chapter) || CHAPTERS[0];
}

export function getChapterLevels(chapter: number): LevelConfig[] {
  return CAMPAIGN_LEVELS.filter((l) => l.chapter === chapter);
}

export function getLevelConfig(levelId: number): LevelConfig {
  return CAMPAIGN_LEVELS.find((l) => l.id === levelId) || CAMPAIGN_LEVELS[0];
}
