import { VehicleConfig, LevelConfig } from '../types/game';
import { ZombieConfig, ZombieType } from '../types/zombie';
import packageJson from '../../package.json';

export const GAME_VERSION = packageJson.version;

export const ARENA_SIZE = 160; // 160x160 units arena
export const ARENA_HALF = ARENA_SIZE / 2;

export const VEHICLES: Record<string, VehicleConfig> = {
  iron_fang: {
    id: 'iron_fang',
    name: 'Iron Fang',
    nameRu: 'Железный Клык',
    descriptionRu: 'Сбалансированный бронемасл-кар с острым шипастым бампером и отличным контролем заноса.',
    price: 0,
    unlocked: true,
    baseStats: {
      maxHealth: 60,
      topSpeed: 26,
      acceleration: 30,
      handling: 3.6,
      driftGrip: 0.88,
      ramDamage: 18,
      nitroDuration: 1.5,
      nitroRefillRate: 0.18,
    },
    color: 0x1a1a1a,
    accentColor: 0xd62828,
  },
  dune_reaper: {
    id: 'dune_reaper',
    name: 'Dune Reaper',
    nameRu: 'Жнец Дюн',
    descriptionRu: 'Легкий скоростной багги для безумного дрифта на 360° и мгновенного набора нитро-ярости.',
    price: 300,
    unlocked: false,
    baseStats: {
      maxHealth: 45,
      topSpeed: 30,
      acceleration: 38,
      handling: 4.4,
      driftGrip: 0.78,
      ramDamage: 14,
      nitroDuration: 1.8,
      nitroRefillRate: 0.25,
    },
    color: 0x2b2b1a,
    accentColor: 0xf77f00,
  },
  war_titan: {
    id: 'war_titan',
    name: 'War Titan',
    nameRu: 'Титан Войны',
    descriptionRu: 'Тяжелый 6-колесный броневик-таран с непробиваемой броней и сокрушительным уроном.',
    price: 650,
    unlocked: false,
    baseStats: {
      maxHealth: 110,
      topSpeed: 21,
      acceleration: 24,
      handling: 2.8,
      driftGrip: 0.92,
      ramDamage: 30,
      nitroDuration: 1.4,
      nitroRefillRate: 0.13,
    },
    color: 0x25302b,
    accentColor: 0x00b4d8,
  },
};

export const ZOMBIE_CONFIGS: Record<ZombieType, ZombieConfig> = {
  WALKER: {
    type: 'WALKER',
    nameRu: 'Ходок',
    maxHealth: 35,
    speed: 5.2,
    turnSpeed: 2.2,
    damage: 10,
    attackRange: 1.8,
    attackCooldown: 0.9,
    mass: 1.0,
    scrapDropMin: 1,
    scrapDropMax: 3,
    xpValue: 12,
    scale: 1.0,
    color: 0x3d5a45,
    accentColor: 0x8a2be2,
  },
  RUNNER: {
    type: 'RUNNER',
    nameRu: 'Бегун',
    maxHealth: 22,
    speed: 9.5,
    turnSpeed: 3.8,
    damage: 8,
    attackRange: 1.5,
    attackCooldown: 0.7,
    mass: 0.8,
    scrapDropMin: 2,
    scrapDropMax: 4,
    xpValue: 16,
    scale: 0.88,
    color: 0x7c3f3f,
    accentColor: 0xff3333,
  },
  SPITTER: {
    type: 'SPITTER',
    nameRu: 'Плевальщик',
    maxHealth: 45,
    speed: 4.5,
    turnSpeed: 2.0,
    damage: 16,
    attackRange: 16.0,
    attackCooldown: 2.4,
    mass: 1.2,
    scrapDropMin: 3,
    scrapDropMax: 6,
    xpValue: 25,
    scale: 1.15,
    color: 0x556b2f,
    accentColor: 0x76ff03,
  },
  TANK: {
    type: 'TANK',
    nameRu: 'Брут-Громила',
    maxHealth: 160,
    speed: 5.8,
    turnSpeed: 1.8,
    damage: 26,
    attackRange: 2.5,
    attackCooldown: 1.4,
    mass: 3.5,
    scrapDropMin: 10,
    scrapDropMax: 18,
    xpValue: 55,
    scale: 1.6,
    color: 0x4a4036,
    accentColor: 0xffaa00,
  },
  BOSS_GOLIATH: {
    type: 'BOSS_GOLIATH',
    nameRu: 'Голиаф Пожиратель',
    maxHealth: 1400,
    speed: 7.0,
    turnSpeed: 1.5,
    damage: 45,
    attackRange: 3.8,
    attackCooldown: 1.8,
    mass: 10.0,
    scrapDropMin: 90,
    scrapDropMax: 140,
    xpValue: 400,
    scale: 2.6,
    color: 0x221111,
    accentColor: 0xff0044,
  },
  BOSS_SAND_TITAN: {
    type: 'BOSS_SAND_TITAN',
    nameRu: 'Голиаф Песчаный Титан',
    maxHealth: 1800,
    speed: 7.2,
    turnSpeed: 1.6,
    damage: 50,
    attackRange: 4.0,
    attackCooldown: 1.8,
    mass: 11.0,
    scrapDropMin: 120,
    scrapDropMax: 180,
    xpValue: 500,
    scale: 2.7,
    color: 0x7a6345,
    accentColor: 0xff9f1c,
  },
  BOSS_IRON_BUTCHER: {
    type: 'BOSS_IRON_BUTCHER',
    nameRu: 'Железный Мясник',
    maxHealth: 2300,
    speed: 7.6,
    turnSpeed: 1.8,
    damage: 55,
    attackRange: 3.6,
    attackCooldown: 1.5,
    mass: 12.0,
    scrapDropMin: 160,
    scrapDropMax: 240,
    xpValue: 650,
    scale: 2.8,
    color: 0x2f3e46,
    accentColor: 0x84a98c,
  },
  BOSS_TOXIC_BEHEMOTH: {
    type: 'BOSS_TOXIC_BEHEMOTH',
    nameRu: 'Токсичный Бегемот',
    maxHealth: 2800,
    speed: 6.5,
    turnSpeed: 1.4,
    damage: 60,
    attackRange: 18.0,
    attackCooldown: 2.0,
    mass: 13.0,
    scrapDropMin: 200,
    scrapDropMax: 300,
    xpValue: 800,
    scale: 2.9,
    color: 0x283618,
    accentColor: 0x76ff03,
  },
  BOSS_INFERNO_TITAN: {
    type: 'BOSS_INFERNO_TITAN',
    nameRu: 'Инферно-Титан',
    maxHealth: 3400,
    speed: 7.8,
    turnSpeed: 1.7,
    damage: 68,
    attackRange: 4.2,
    attackCooldown: 1.6,
    mass: 14.0,
    scrapDropMin: 250,
    scrapDropMax: 380,
    xpValue: 1000,
    scale: 3.0,
    color: 0x3d0000,
    accentColor: 0xff4500,
  },
  BOSS_CYBER_REAPER: {
    type: 'BOSS_CYBER_REAPER',
    nameRu: 'Неоновый Кибер-Жнец',
    maxHealth: 3900,
    speed: 9.2,
    turnSpeed: 2.5,
    damage: 72,
    attackRange: 3.8,
    attackCooldown: 1.2,
    mass: 11.5,
    scrapDropMin: 320,
    scrapDropMax: 480,
    xpValue: 1250,
    scale: 2.7,
    color: 0x03071e,
    accentColor: 0x00f0ff,
  },
  BOSS_STORM_BRINGER: {
    type: 'BOSS_STORM_BRINGER',
    nameRu: 'Буревестник Пустоши',
    maxHealth: 4600,
    speed: 8.2,
    turnSpeed: 1.9,
    damage: 78,
    attackRange: 4.5,
    attackCooldown: 1.5,
    mass: 14.5,
    scrapDropMin: 400,
    scrapDropMax: 600,
    xpValue: 1500,
    scale: 3.1,
    color: 0x1d3557,
    accentColor: 0x48cae4,
  },
  BOSS_CRIMSON_REAPER: {
    type: 'BOSS_CRIMSON_REAPER',
    nameRu: 'Кровавый Жнец',
    maxHealth: 5400,
    speed: 9.0,
    turnSpeed: 2.2,
    damage: 85,
    attackRange: 4.0,
    attackCooldown: 1.3,
    mass: 13.5,
    scrapDropMin: 500,
    scrapDropMax: 750,
    xpValue: 1800,
    scale: 2.9,
    color: 0x590d22,
    accentColor: 0xff0054,
  },
  BOSS_RADIOACTIVE_COLOSSUS: {
    type: 'BOSS_RADIOACTIVE_COLOSSUS',
    nameRu: 'Радиоактивный Колосс',
    maxHealth: 6400,
    speed: 7.5,
    turnSpeed: 1.6,
    damage: 92,
    attackRange: 5.0,
    attackCooldown: 1.8,
    mass: 16.0,
    scrapDropMin: 650,
    scrapDropMax: 950,
    xpValue: 2200,
    scale: 3.3,
    color: 0x132a13,
    accentColor: 0x39ff14,
  },
  BOSS_ASHEN_OVERLORD: {
    type: 'BOSS_ASHEN_OVERLORD',
    nameRu: 'Повелитель Пепла',
    maxHealth: 7600,
    speed: 8.4,
    turnSpeed: 1.8,
    damage: 100,
    attackRange: 4.8,
    attackCooldown: 1.5,
    mass: 17.0,
    scrapDropMin: 800,
    scrapDropMax: 1200,
    xpValue: 2700,
    scale: 3.4,
    color: 0x1a1423,
    accentColor: 0xff6b35,
  },
  BOSS_APOCALYPSE_LORD: {
    type: 'BOSS_APOCALYPSE_LORD',
    nameRu: 'Владыка Апокалипсиса',
    maxHealth: 9900,
    speed: 9.0,
    turnSpeed: 2.2,
    damage: 120,
    attackRange: 5.5,
    attackCooldown: 1.3,
    mass: 20.0,
    scrapDropMin: 1500,
    scrapDropMax: 2500,
    xpValue: 4000,
    scale: 3.8,
    color: 0x10002b,
    accentColor: 0x9d4edd,
  },
};

export const GARAGE_UPGRADE_COSTS = {
  hullLevel: [40, 80, 150, 260, 450],
  engineLevel: [40, 90, 170, 290, 500],
  driftLevel: [35, 75, 140, 240, 380],
  ramLevel: [50, 100, 190, 320, 550],
  nitroLevel: [40, 85, 150, 250, 420],
  magnetLevel: [25, 55, 110, 190, 300],
};

export { CAMPAIGN_LEVELS, CHAPTERS, getChapterInfo, getChapterLevels, getLevelConfig } from './CampaignLevels';

