import { VehicleConfig } from '../types/game';
import { ZombieConfig, ZombieType } from '../types/zombie';

export const ARENA_SIZE = 160; // 160x160 units arena
export const ARENA_HALF = ARENA_SIZE / 2;

export const VEHICLES: Record<string, VehicleConfig> = {
  iron_fang: {
    id: 'iron_fang',
    name: 'Iron Fang',
    nameRu: 'Железный Клык',
    descriptionRu: 'Сбалансированный бронемасл-кар с острым шипастым бампером и отличным контролем заноса.',
    price: 0,
    unlocked: true,
    baseStats: {
      maxHealth: 200,
      topSpeed: 28,
      acceleration: 38,
      handling: 3.8,
      driftGrip: 0.88,
      ramDamage: 65,
      nitroDuration: 3.5,
      nitroRefillRate: 0.35,
    },
    color: 0x1a1a1a,
    accentColor: 0xd62828,
  },
  dune_reaper: {
    id: 'dune_reaper',
    name: 'Dune Reaper',
    nameRu: 'Жнец Дюн',
    descriptionRu: 'Легкий песчаный багги для безумного дрифта на 360° и молниеносного набора нитро-ярости.',
    price: 350,
    unlocked: false,
    baseStats: {
      maxHealth: 150,
      topSpeed: 34,
      acceleration: 48,
      handling: 4.6,
      driftGrip: 0.78,
      ramDamage: 50,
      nitroDuration: 4.2,
      nitroRefillRate: 0.55,
    },
    color: 0x2b2b1a,
    accentColor: 0xf77f00,
  },
  war_titan: {
    id: 'war_titan',
    name: 'War Titan',
    nameRu: 'Титан Войны',
    descriptionRu: 'Тяжелый 6-колесный броневик-таран. Разрывает орды зомби в клочья одним ударом решетки.',
    price: 800,
    unlocked: false,
    baseStats: {
      maxHealth: 350,
      topSpeed: 24,
      acceleration: 30,
      handling: 3.0,
      driftGrip: 0.92,
      ramDamage: 120,
      nitroDuration: 3.0,
      nitroRefillRate: 0.28,
    },
    color: 0x25302b,
    accentColor: 0x00b4d8,
  },
};

export const ZOMBIE_CONFIGS: Record<ZombieType, ZombieConfig> = {
  WALKER: {
    type: 'WALKER',
    nameRu: 'Ходок',
    maxHealth: 40,
    speed: 5.5,
    turnSpeed: 2.2,
    damage: 10,
    attackRange: 1.8,
    attackCooldown: 1.0,
    mass: 1.0,
    scrapDropMin: 1,
    scrapDropMax: 3,
    xpValue: 10,
    scale: 1.0,
    color: 0x3d5a45,
    accentColor: 0x8a2be2,
  },
  RUNNER: {
    type: 'RUNNER',
    nameRu: 'Бегун',
    maxHealth: 25,
    speed: 10.5,
    turnSpeed: 3.8,
    damage: 8,
    attackRange: 1.5,
    attackCooldown: 0.7,
    mass: 0.8,
    scrapDropMin: 2,
    scrapDropMax: 4,
    xpValue: 15,
    scale: 0.88,
    color: 0x7c3f3f,
    accentColor: 0xff3333,
  },
  SPITTER: {
    type: 'SPITTER',
    nameRu: 'Плевальщик',
    maxHealth: 50,
    speed: 4.5,
    turnSpeed: 2.0,
    damage: 15,
    attackRange: 16.0,
    attackCooldown: 2.5,
    mass: 1.2,
    scrapDropMin: 3,
    scrapDropMax: 6,
    xpValue: 25,
    scale: 1.15,
    color: 0x556b2f,
    accentColor: 0x76ff03,
  },
  TANK: {
    type: 'TANK',
    nameRu: 'Брут-Громила',
    maxHealth: 180,
    speed: 6.0,
    turnSpeed: 1.8,
    damage: 28,
    attackRange: 2.5,
    attackCooldown: 1.5,
    mass: 3.5,
    scrapDropMin: 8,
    scrapDropMax: 15,
    xpValue: 50,
    scale: 1.6,
    color: 0x4a4036,
    accentColor: 0xffaa00,
  },
  BOSS_GOLIATH: {
    type: 'BOSS_GOLIATH',
    nameRu: 'Голиаф Пожиратель',
    maxHealth: 1500,
    speed: 7.5,
    turnSpeed: 1.5,
    damage: 45,
    attackRange: 3.8,
    attackCooldown: 1.8,
    mass: 10.0,
    scrapDropMin: 80,
    scrapDropMax: 120,
    xpValue: 350,
    scale: 2.6,
    color: 0x221111,
    accentColor: 0xff0044,
  },
};

export const GARAGE_UPGRADE_COSTS = {
  hullLevel: [50, 100, 180, 300, 500],
  engineLevel: [50, 110, 200, 320, 550],
  driftLevel: [40, 90, 160, 260, 420],
  ramLevel: [60, 130, 220, 360, 600],
  nitroLevel: [50, 100, 170, 280, 480],
  magnetLevel: [30, 70, 130, 220, 350],
};
