import { VehicleConfig } from '../types/game';
import { ZombieConfig, ZombieType } from '../types/zombie';
import packageJson from '../../package.json';

export const GAME_VERSION = packageJson.version;

export const ARENA_SIZE = 160; // 160x160 units arena
export const ARENA_HALF = ARENA_SIZE / 2;

export const VEHICLES: Record<string, VehicleConfig> = {
  iron_fang: {
    id: 'iron_fang',
    name: 'Iron Fang',
    nameRu: 'Железный Клык',
    descriptionRu: 'Сбалансированный бронемасл-кар с острым шипастым бампером и контролем заноса.',
    price: 0,
    unlocked: true,
    baseStats: {
      maxHealth: 60,
      topSpeed: 26,
      acceleration: 30,
      handling: 3.6,
      driftGrip: 0.88,
      ramDamage: 18,
      nitroDuration: 1.5,
      nitroRefillRate: 0.18,
    },
    color: 0x1a1a1a,
    accentColor: 0xd62828,
  },
  dune_reaper: {
    id: 'dune_reaper',
    name: 'Dune Reaper',
    nameRu: 'Жнец Дюн',
    descriptionRu: 'Легкий песчаный багги для безумного дрифта на 360° и быстрого набора нитро-ярости.',
    price: 300,
    unlocked: false,
    baseStats: {
      maxHealth: 45,
      topSpeed: 30,
      acceleration: 38,
      handling: 4.4,
      driftGrip: 0.78,
      ramDamage: 14,
      nitroDuration: 1.8,
      nitroRefillRate: 0.25,
    },
    color: 0x2b2b1a,
    accentColor: 0xf77f00,
  },
  war_titan: {
    id: 'war_titan',
    name: 'War Titan',
    nameRu: 'Титан Войны',
    descriptionRu: 'Тяжелый 6-колесный броневик-таран с повышенной прочностью кузова.',
    price: 650,
    unlocked: false,
    baseStats: {
      maxHealth: 110,
      topSpeed: 21,
      acceleration: 24,
      handling: 2.8,
      driftGrip: 0.92,
      ramDamage: 30,
      nitroDuration: 1.4,
      nitroRefillRate: 0.13,
    },
    color: 0x25302b,
    accentColor: 0x00b4d8,
  },
};

export const ZOMBIE_CONFIGS: Record<ZombieType, ZombieConfig> = {
  WALKER: {
    type: 'WALKER',
    nameRu: 'Ходок',
    maxHealth: 35,
    speed: 5.2,
    turnSpeed: 2.2,
    damage: 10,
    attackRange: 1.8,
    attackCooldown: 0.9,
    mass: 1.0,
    scrapDropMin: 1,
    scrapDropMax: 3,
    xpValue: 12,
    scale: 1.0,
    color: 0x3d5a45,
    accentColor: 0x8a2be2,
  },
  RUNNER: {
    type: 'RUNNER',
    nameRu: 'Бегун',
    maxHealth: 22,
    speed: 9.5,
    turnSpeed: 3.8,
    damage: 8,
    attackRange: 1.5,
    attackCooldown: 0.7,
    mass: 0.8,
    scrapDropMin: 2,
    scrapDropMax: 4,
    xpValue: 16,
    scale: 0.88,
    color: 0x7c3f3f,
    accentColor: 0xff3333,
  },
  SPITTER: {
    type: 'SPITTER',
    nameRu: 'Плевальщик',
    maxHealth: 45,
    speed: 4.5,
    turnSpeed: 2.0,
    damage: 16,
    attackRange: 16.0,
    attackCooldown: 2.4,
    mass: 1.2,
    scrapDropMin: 3,
    scrapDropMax: 6,
    xpValue: 25,
    scale: 1.15,
    color: 0x556b2f,
    accentColor: 0x76ff03,
  },
  TANK: {
    type: 'TANK',
    nameRu: 'Брут-Громила',
    maxHealth: 160,
    speed: 5.8,
    turnSpeed: 1.8,
    damage: 26,
    attackRange: 2.5,
    attackCooldown: 1.4,
    mass: 3.5,
    scrapDropMin: 10,
    scrapDropMax: 18,
    xpValue: 55,
    scale: 1.6,
    color: 0x4a4036,
    accentColor: 0xffaa00,
  },
  BOSS_GOLIATH: {
    type: 'BOSS_GOLIATH',
    nameRu: 'Голиаф Пожиратель',
    maxHealth: 1400,
    speed: 7.0,
    turnSpeed: 1.5,
    damage: 45,
    attackRange: 3.8,
    attackCooldown: 1.8,
    mass: 10.0,
    scrapDropMin: 90,
    scrapDropMax: 140,
    xpValue: 400,
    scale: 2.6,
    color: 0x221111,
    accentColor: 0xff0044,
  },
};

export const GARAGE_UPGRADE_COSTS = {
  hullLevel: [40, 80, 150, 260, 450],
  engineLevel: [40, 90, 170, 290, 500],
  driftLevel: [35, 75, 140, 240, 380],
  ramLevel: [50, 100, 190, 320, 550],
  nitroLevel: [40, 85, 150, 250, 420],
  magnetLevel: [25, 55, 110, 190, 300],
};
